{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-legacy",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.24.0.jar",
          "url": "adventure-text-serializer-legacy-4.24.0.jar",
          "size": 29764,
          "sha512": "5c0edce662923962da01a6e43bbf61f2eac862db0ea10ca41fe607138f09256359fb51c88e09c4dcb80993a649db76d97d62bc89266c45678afce96b1728bb33",
          "sha256": "40ed53afe2a7d668b814add69de15acf4bda8e9f951c4e5d4e224d777054685e",
          "sha1": "5361cdc81313bdd83aae0ce792e103e551c7dbec",
          "md5": "d059e8c73caf427505d5c8411b133d80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.24.0.jar",
          "url": "adventure-text-serializer-legacy-4.24.0.jar",
          "size": 29764,
          "sha512": "5c0edce662923962da01a6e43bbf61f2eac862db0ea10ca41fe607138f09256359fb51c88e09c4dcb80993a649db76d97d62bc89266c45678afce96b1728bb33",
          "sha256": "40ed53afe2a7d668b814add69de15acf4bda8e9f951c4e5d4e224d777054685e",
          "sha1": "5361cdc81313bdd83aae0ce792e103e551c7dbec",
          "md5": "d059e8c73caf427505d5c8411b133d80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.24.0-javadoc.jar",
          "url": "adventure-text-serializer-legacy-4.24.0-javadoc.jar",
          "size": 106148,
          "sha512": "13eca4f6354790aca17a806bec74fffb5d6dc92286e5416c275e53f76dd303c2e695d7fc06e003b014f735253b879710c104807620a30d85b97ce4d65a182929",
          "sha256": "698e0e84887a131208b55c4184f5e8b9cfe3984399e9f3ae84524aa91955560a",
          "sha1": "580b22b52d7baf29c9da9036e82ad3625f590186",
          "md5": "c8956050c6e8d227acbb7a30860b0ac1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.24.0-sources.jar",
          "url": "adventure-text-serializer-legacy-4.24.0-sources.jar",
          "size": 18534,
          "sha512": "abfb5a428ae16ae19f640e997bdcaecdd801af3b9c0809f79b7fbf3f8c0181286ba5452646b216417b16deee041534345385f6f0c1a3ff9045c4eed38c8098df",
          "sha256": "ecd0dec2c390653081b6b533b2422bdad8fdaf562f071bb24c0d46501d0ac8da",
          "sha1": "82501fc88f4ec8655ae19936975295f9f9bf53fb",
          "md5": "b18f847d8567476ec3278143ab95047c"
        }
      ]
    }
  ]
}
