{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-nbt",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.26.1.jar",
          "url": "adventure-nbt-4.26.1.jar",
          "size": 106264,
          "sha512": "6802c32b66041d4fd4076ad067362c2cdb7fc395d89a5ac9952dc91574b4835c5b55d3285ae04429066f9759b385f2dc887bb9f188c252de6ebaa4dc3479f457",
          "sha256": "f26ef6bff5fcdd817902b4dfd353561d98cb131b4ecb67341ff00ef2ed1336f8",
          "sha1": "849df2d41787a88bc50d83a7a7a48de10e40bbdc",
          "md5": "04c5194709280ecbef2a6f3d6123909e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.26.1.jar",
          "url": "adventure-nbt-4.26.1.jar",
          "size": 106264,
          "sha512": "6802c32b66041d4fd4076ad067362c2cdb7fc395d89a5ac9952dc91574b4835c5b55d3285ae04429066f9759b385f2dc887bb9f188c252de6ebaa4dc3479f457",
          "sha256": "f26ef6bff5fcdd817902b4dfd353561d98cb131b4ecb67341ff00ef2ed1336f8",
          "sha1": "849df2d41787a88bc50d83a7a7a48de10e40bbdc",
          "md5": "04c5194709280ecbef2a6f3d6123909e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.26.1-javadoc.jar",
          "url": "adventure-nbt-4.26.1-javadoc.jar",
          "size": 188247,
          "sha512": "1930472cdee467395eb4e6cec3a9ed9eb87be42c4858c1a55ef33ffff1babb36b71254a760c9e697f8d13e4dd4c7f817604b2a5df3e0bb6776cc9354b94c18f4",
          "sha256": "2eb5b07ac418ddf760a7b52d0fdca12e66746f851ff06de04d34f41fb358b6ac",
          "sha1": "26a58a4134c793e535b80233a1a39a85e4f0e5bf",
          "md5": "64392a9f90d6f8824f2390074826e569"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-nbt-4.26.1-sources.jar",
          "url": "adventure-nbt-4.26.1-sources.jar",
          "size": 88348,
          "sha512": "f5630b93d9b03315edafa0f36f884dcfe4c8950ada68666d4f160573bae698078d60904c36cd973aeb7580a289f69ae0517d89ba18bf16d4f37280a3481273a0",
          "sha256": "be29a3f8964b63067e627dabb7bb9761fbc0387262fa18607a760de4bd7dfe7c",
          "sha1": "9183202a5ad2cc4febc0432779f45a772a6f93d0",
          "md5": "770e7531ff98cd04b04fce52ed37e71b"
        }
      ]
    }
  ]
}
