{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-gson",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.21.0.jar",
          "url": "adventure-text-serializer-gson-4.21.0.jar",
          "size": 60450,
          "sha512": "c39923657b1601c7f06ac0ad801d3345711ec580aa77f7fa4fe1edc078f0aa5ad67fec611ad35077047c0233ed8a4950bda96dd11340c7749b5790c39d2b0f8b",
          "sha256": "39b51cfa9a04df6e1d2f431d26a697ed619623696cdeb1c00a1afd347c5ce084",
          "sha1": "bead7313df3c17c0b117b4e92a7e9a8d86b57d3a",
          "md5": "1dc38ef55737a7c3a628ff0fb5964cf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-commons",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.21.0.jar",
          "url": "adventure-text-serializer-gson-4.21.0.jar",
          "size": 60450,
          "sha512": "c39923657b1601c7f06ac0ad801d3345711ec580aa77f7fa4fe1edc078f0aa5ad67fec611ad35077047c0233ed8a4950bda96dd11340c7749b5790c39d2b0f8b",
          "sha256": "39b51cfa9a04df6e1d2f431d26a697ed619623696cdeb1c00a1afd347c5ce084",
          "sha1": "bead7313df3c17c0b117b4e92a7e9a8d86b57d3a",
          "md5": "1dc38ef55737a7c3a628ff0fb5964cf3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.21.0-javadoc.jar",
          "url": "adventure-text-serializer-gson-4.21.0-javadoc.jar",
          "size": 109675,
          "sha512": "c42f8834c5e8f58d6cee9e81c84976dcea2ec9c402c59cf1d7d61e26d7bece0c39c3c326fd94a2872c0cc08d4758071074d9bb8d5912cc926e3d633e6787b3d0",
          "sha256": "e8584319036828fc61a691055f411bcdeb112536168cedd9416d9e860a2a13da",
          "sha1": "bdb5611b00ac81239c74747a3e9bfd0b1b7e7503",
          "md5": "f30da6934eff1e8d7036db057677708d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.21.0-sources.jar",
          "url": "adventure-text-serializer-gson-4.21.0-sources.jar",
          "size": 44370,
          "sha512": "536198f7fbc995f27c49a05058d1d4953238cd1ae1880706fe4116acdacf0a7932a491835c9a0a9b0feaf81e569d549924c55852b81a20bf36a256a2ca048622",
          "sha256": "6dfd1bbba5a3a27291499df19f3e79e5e3d270657ac6bd1c5e31b4d59f98c6c1",
          "sha1": "83f0058dac994e4f6350705f64f1e9f734f06437",
          "md5": "c3c585dc112e6df492b4b81bc01121da"
        }
      ]
    }
  ]
}
