{
  "formatVersion": "1.1",
  "component": {
    "group": "net.essentialsx",
    "module": "PaperProvider",
    "version": "2.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PaperProvider-2.21.0.jar",
          "url": "PaperProvider-2.21.0.jar",
          "size": 19226,
          "sha512": "52bb5398a051febf14262ed5dbd42f82f7afdae9bbc101f7a09b4ab3a88b26860ce8a7615940f26fa4aa0d0c11c6cba2ec8c56a7ab5d42e87032cfd1313c8786",
          "sha256": "b927ff9727c3cbf71551680bc25d4b1d63b745ecc1d036bfe0b10094f4b458f9",
          "sha1": "6676a32f10ce74f885f5a263d5099002c3a58540",
          "md5": "3acc854374538638ae1612507131764a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.essentialsx",
          "module": "BaseProviders",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spigot-api"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          },
          "reason": "Bukkit API ships old versions, Configurate requires modern versions"
        }
      ],
      "files": [
        {
          "name": "PaperProvider-2.21.0.jar",
          "url": "PaperProvider-2.21.0.jar",
          "size": 19226,
          "sha512": "52bb5398a051febf14262ed5dbd42f82f7afdae9bbc101f7a09b4ab3a88b26860ce8a7615940f26fa4aa0d0c11c6cba2ec8c56a7ab5d42e87032cfd1313c8786",
          "sha256": "b927ff9727c3cbf71551680bc25d4b1d63b745ecc1d036bfe0b10094f4b458f9",
          "sha1": "6676a32f10ce74f885f5a263d5099002c3a58540",
          "md5": "3acc854374538638ae1612507131764a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PaperProvider-2.21.0-javadoc.jar",
          "url": "PaperProvider-2.21.0-javadoc.jar",
          "size": 134005,
          "sha512": "9085176cc2cad065bc475586bf76fa6b2e89e032a60c9c433794aba9c7baf737ee5ec8d13e1a36b0552c1d07337f128bb082ea6410cb30cb0f7aa59203489c6b",
          "sha256": "7cc6476b7f1843fe609c4988197703d7753236ad94c1ee62a23cf5d4b7beefc7",
          "sha1": "72e00cb51bac9ccdd048821ed39512b35625778d",
          "md5": "05aa95ab2a456c97617a475d23d75953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PaperProvider-2.21.0-sources.jar",
          "url": "PaperProvider-2.21.0-sources.jar",
          "size": 10230,
          "sha512": "893b863dbb6f032887f24eadcfdb54188899f8e42851d1674a3e8bf39cbd4920e3dc8294a4ed51dafec8c7463c44dfd6d389bb3a6fcecdf6e3886966030a8309",
          "sha256": "3a7921992e1e5cdcb9788f40c577028f8449afa948c6320187a245c0b79d58d7",
          "sha1": "cc297b300e732459543fac8c8fec679a61189cc5",
          "md5": "f203562a95d595dc6abff5fa881a6ead"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PaperProvider-2.21.0-all.jar",
          "url": "PaperProvider-2.21.0-all.jar",
          "size": 59540,
          "sha512": "fe5afee0d820fd3d15724a9d0c479c655f67c1f368676ba7c2e2fa5f658e5ed2ad18b46782a7f93dd8fea80e8ce50aa74506cab4af657e7df6be2aa41758480b",
          "sha256": "ecd4f022cf256a8f12bb2e6144fe92d37ad5a100baf227bd9800fc315f6b5404",
          "sha1": "7536ed4f72f877766e160b2a002719745747855c",
          "md5": "31587dc391c4d391876b1b233b770d04"
        }
      ]
    }
  ]
}
