{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-key",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.24.0.jar",
          "url": "adventure-key-4.24.0.jar",
          "size": 11369,
          "sha512": "ec4a48d298a0b98918e01cb7a6c0462b835b16f0d81077b3edf11371a048ce7c90621fe8d42906e1eb2fa5d37633f351aef6379164188d2ff180983bf71cb1ef",
          "sha256": "d4f21f4281e89dab345a9004567668794819f9cc483eaff8bfd64c57494a9150",
          "sha1": "ac70a5ba3c5485658da032044f127f824613f63a",
          "md5": "92e2c79a898f506a957d2005a286db1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.24.0.jar",
          "url": "adventure-key-4.24.0.jar",
          "size": 11369,
          "sha512": "ec4a48d298a0b98918e01cb7a6c0462b835b16f0d81077b3edf11371a048ce7c90621fe8d42906e1eb2fa5d37633f351aef6379164188d2ff180983bf71cb1ef",
          "sha256": "d4f21f4281e89dab345a9004567668794819f9cc483eaff8bfd64c57494a9150",
          "sha1": "ac70a5ba3c5485658da032044f127f824613f63a",
          "md5": "92e2c79a898f506a957d2005a286db1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.24.0-javadoc.jar",
          "url": "adventure-key-4.24.0-javadoc.jar",
          "size": 105656,
          "sha512": "2c57387d4b877819eeb019604bcda17e78a7c15abde721fde36880cc28d59398d85734512a24cccce1fc972ef52fb9df55883865b708548ce799baff724962e4",
          "sha256": "03f91924c15c9d965d29135f56d9ee1089f4c2d6ff99456bd7fc5f65b21cde72",
          "sha1": "35cd5246cfb45e81b7355b8994c021762f7deda5",
          "md5": "b6b9172b81a7bc77937ef2022038eafc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-key-4.24.0-sources.jar",
          "url": "adventure-key-4.24.0-sources.jar",
          "size": 13405,
          "sha512": "6ab2c94f6f3cc45eeb181634b186630b9e4967dc21b6bf637401c5e7aa118cb6f3ad524915002d876b5105f337811dfdc355422d5f00759e694a8e9002de8901",
          "sha256": "133cc1f89181ac4618219e985c8a12ca9db3164b9942cdd68b10917c21334c2b",
          "sha1": "754f157c636fd0eb9733553912a8bf97d6437f0b",
          "md5": "308ea94db11fd0c8de8d542226e6a020"
        }
      ]
    }
  ]
}
