{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-logger-slf4j",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-logger-slf4j-4.24.0.jar",
          "url": "adventure-text-logger-slf4j-4.24.0.jar",
          "size": 19942,
          "sha512": "f800675192a1eccf4214e49a2de703951d62c42fb2f223862a5de2d84953fbc43381f5f3bde26d8b35e56605e38c85789a3ea3700293082adbbbd32db9da635a",
          "sha256": "22e30a6e92a70e0a442eb64c906524a776f3c303e285e183cf2b7c435f90a81c",
          "sha1": "c0e71d049e01b5f98f1ff5e01d0cb5e2db61a11e",
          "md5": "5c04e58a4afe3380186e6b85d4e2315d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-logger-slf4j-4.24.0.jar",
          "url": "adventure-text-logger-slf4j-4.24.0.jar",
          "size": 19942,
          "sha512": "f800675192a1eccf4214e49a2de703951d62c42fb2f223862a5de2d84953fbc43381f5f3bde26d8b35e56605e38c85789a3ea3700293082adbbbd32db9da635a",
          "sha256": "22e30a6e92a70e0a442eb64c906524a776f3c303e285e183cf2b7c435f90a81c",
          "sha1": "c0e71d049e01b5f98f1ff5e01d0cb5e2db61a11e",
          "md5": "5c04e58a4afe3380186e6b85d4e2315d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-logger-slf4j-4.24.0-javadoc.jar",
          "url": "adventure-text-logger-slf4j-4.24.0-javadoc.jar",
          "size": 92409,
          "sha512": "b6c392e418ee43d0212a9db6054b213f93151fc09faee5caadd413ba94d7ee72e207aca8fb15681d1fa227bc6362a7831f525f2f8f565e4fa2de9c98b6786129",
          "sha256": "ac1cff32712951ce12fe95de660f77050e3f57d9083dcc6df627d7510a078c5f",
          "sha1": "73371841a5174618c835d055b7b44e26794c77a1",
          "md5": "0e7fb507aa45c0889e9ea073b0634d1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-logger-slf4j-4.24.0-sources.jar",
          "url": "adventure-text-logger-slf4j-4.24.0-sources.jar",
          "size": 16908,
          "sha512": "1b1671864da4119ac546e725cf19fdc1d285c7a06d8d96e59641569ddd97d04de57400cc3534077a258af7421aa5c7fcab9fe3139bc42fb1a2c48d412ff588e2",
          "sha256": "e0d8d229ea9bfb7abd0a0fc27d6f2920fafb3af752a5325cfd89035436b3e257",
          "sha1": "15a2858b8b3444d52f296e186f3adde143b53ee1",
          "md5": "88f63a252502db6440d7b639cc5f82c2"
        }
      ]
    }
  ]
}
