{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-json",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-4.24.0.jar",
          "url": "adventure-text-serializer-json-4.24.0.jar",
          "size": 16980,
          "sha512": "bcf87d6663f779bed7b3f95e7888508510da516c48f1fdb205ca660e4c95792ec7ca483dde25a77cbc83ac83cec2f1dc32d3ff06c09cedcfedbe9f76064a0e96",
          "sha256": "ff6a80344cbf14d6a751947caf9db9669dd0740aeac8cc555c9b8648ff5771b2",
          "sha1": "303b4fa233fc60b025a22a399049c726640d004c",
          "md5": "1c13355bc90057d6cc209f787aafffa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-commons",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-4.24.0.jar",
          "url": "adventure-text-serializer-json-4.24.0.jar",
          "size": 16980,
          "sha512": "bcf87d6663f779bed7b3f95e7888508510da516c48f1fdb205ca660e4c95792ec7ca483dde25a77cbc83ac83cec2f1dc32d3ff06c09cedcfedbe9f76064a0e96",
          "sha256": "ff6a80344cbf14d6a751947caf9db9669dd0740aeac8cc555c9b8648ff5771b2",
          "sha1": "303b4fa233fc60b025a22a399049c726640d004c",
          "md5": "1c13355bc90057d6cc209f787aafffa1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-4.24.0-javadoc.jar",
          "url": "adventure-text-serializer-json-4.24.0-javadoc.jar",
          "size": 122375,
          "sha512": "035b5197e58d5d76428ab30907b6bb7ba7e2eb7e74e1ec99e75e2ae21d7d5c8d55d749643fbc125958e7de4fda3f7877734b936377075b4e327cb53f82b5bff1",
          "sha256": "169520f55de1ecb81c48ed8f56ed9e66abe241ea7d820a7dcd52779d6ec661b4",
          "sha1": "f9e76cdb94d415f8deb100754355591f974d5c75",
          "md5": "d594e661be72224b5de07afa2f512eb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-json-4.24.0-sources.jar",
          "url": "adventure-text-serializer-json-4.24.0-sources.jar",
          "size": 12632,
          "sha512": "fdd3f2ad4284b39e209226965ae78d5820e5f65586f8a6d96eea5db261d3d8245efefd8156ee9b129e389de6b1fc8e9827c558f36937f236467e03ebe5bd669d",
          "sha256": "11fb47a9b1238935b4a0f214c4b55eaf92aa7f309efb98b38274d13e6a7d2e2b",
          "sha1": "c884b03f115b4cecb6fae8f2dc2adeb664e34ae2",
          "md5": "50941d61d1e00ce037b3a6feb5b3651c"
        }
      ]
    }
  ]
}
