{
  "formatVersion": "1.1",
  "component": {
    "group": "net.essentialsx",
    "module": "1_8Provider",
    "version": "2.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "1_8Provider-2.21.0.jar",
          "url": "1_8Provider-2.21.0.jar",
          "size": 12059,
          "sha512": "335b4bc34848bf74b1ce8410ea5d91609eba094063f10690fd3607073789cf32a973515968b65437366460c59e0a0469cc32f16d7c2cda578ceb021fb375d309",
          "sha256": "9218ef634681c226d64d64d40a580a9118a5790f8443f235db477cdc0a5ab649",
          "sha1": "03fa8a1d584a81bf29bda56d5dce61d7adb64768",
          "md5": "90958a9de7b00ac3287e9f344aae60c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.essentialsx",
          "module": "BaseProviders",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.spigotmc",
              "module": "spigot-api"
            }
          ]
        },
        {
          "group": "org.spigotmc",
          "module": "spigot-api",
          "version": {
            "requires": "1.8.8-R0.1-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          },
          "reason": "Bukkit API ships old versions, Configurate requires modern versions"
        }
      ],
      "files": [
        {
          "name": "1_8Provider-2.21.0.jar",
          "url": "1_8Provider-2.21.0.jar",
          "size": 12059,
          "sha512": "335b4bc34848bf74b1ce8410ea5d91609eba094063f10690fd3607073789cf32a973515968b65437366460c59e0a0469cc32f16d7c2cda578ceb021fb375d309",
          "sha256": "9218ef634681c226d64d64d40a580a9118a5790f8443f235db477cdc0a5ab649",
          "sha1": "03fa8a1d584a81bf29bda56d5dce61d7adb64768",
          "md5": "90958a9de7b00ac3287e9f344aae60c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1_8Provider-2.21.0-javadoc.jar",
          "url": "1_8Provider-2.21.0-javadoc.jar",
          "size": 132002,
          "sha512": "3e29776d47b7f025dec6b60f6177889c543f16300db89daf834d633770e85de22c5b9b2baa97db65a18f78fffb0eca388fb819efa6d146dda52232385044adcf",
          "sha256": "2418303f86c0cb6b20d6923d896fd461446227fc68f20849fc609dcaf421829f",
          "sha1": "068c5b9d28abad124ccf6d7ec813f56579c40680",
          "md5": "c8d2d25715641f9fb5fccfd6f12f91fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1_8Provider-2.21.0-sources.jar",
          "url": "1_8Provider-2.21.0-sources.jar",
          "size": 6512,
          "sha512": "2f6ce8abe928f3fdb7ffba3b10fb0bb9aa2daf000757997881bf209af36224b77e0d7ceb860141064a88f76138e4133cc32b86e5fe698492a59f60d57976ec88",
          "sha256": "ca87e12561b36fa3e0990346514c46da802ecf658a602cc98525f4065b9c36ad",
          "sha1": "fa790b60451888522f19845956b6fbcc5e2f1ef0",
          "md5": "edb2d12769d9b80d0adbf64474ab165f"
        }
      ]
    }
  ]
}
