{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-platform-facet",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-facet-4.4.1.jar",
          "url": "adventure-platform-facet-4.4.1.jar",
          "size": 43186,
          "sha512": "5b03ef6ce6a08d8d38b151fdb3b35da35e2d533a2ae7a017d63f4a0f59845154b370a9924cbd43801bf2740445b9ad4248a3e95ed016076e9ef845d5d55351e9",
          "sha256": "20f8e6db34d722a4acccbedcc9b6c02e8ee6b3cab9350b06ab3d1c0b0b8b454f",
          "sha1": "be5c9943891ccee0980ac9becb34e50539e42c6b",
          "md5": "f1c2157458ce8a9ea2aef4d23b986f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-facet-4.4.1.jar",
          "url": "adventure-platform-facet-4.4.1.jar",
          "size": 43186,
          "sha512": "5b03ef6ce6a08d8d38b151fdb3b35da35e2d533a2ae7a017d63f4a0f59845154b370a9924cbd43801bf2740445b9ad4248a3e95ed016076e9ef845d5d55351e9",
          "sha256": "20f8e6db34d722a4acccbedcc9b6c02e8ee6b3cab9350b06ab3d1c0b0b8b454f",
          "sha1": "be5c9943891ccee0980ac9becb34e50539e42c6b",
          "md5": "f1c2157458ce8a9ea2aef4d23b986f11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-facet-4.4.1-javadoc.jar",
          "url": "adventure-platform-facet-4.4.1-javadoc.jar",
          "size": 411877,
          "sha512": "c783e3902c03040780fac976261cd71feb00aa4d2e04f7a9b5590704fdc002365b7b65c8e8a8f42c0a706523435c719f68dd2525f726700b370ecea307a065c5",
          "sha256": "798306a4e3ab42e33e3f4b2edc081e9d6478b09a10b74782704a17add8650f1d",
          "sha1": "d0aaa550da2eebd008d73e21ec6d3e23c8711c58",
          "md5": "8d663a210cd4573d47d7d1c1ce726f68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-platform-facet-4.4.1-sources.jar",
          "url": "adventure-platform-facet-4.4.1-sources.jar",
          "size": 22548,
          "sha512": "255bfa041c96063f55a3508e4157340037263e13f87b8a989fac63f34b2d04e4b501e9762fcba0ac2f6dbaebba042b0475ab0b6e668953ad02bf686a01dd01a5",
          "sha256": "c75464aebaa48223be03fa4fc39944b8334b3694f631bbc2850335c2955a4de7",
          "sha1": "9a8b4c8bf65f7a332ca3406ff9e9320c65b5b59e",
          "md5": "b3bc4aac15583981825f6d5050a28597"
        }
      ]
    }
  ]
}
