{
  "formatVersion": "1.1",
  "component": {
    "group": "net.essentialsx",
    "module": "BaseProviders",
    "version": "2.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.spigotmc",
          "module": "spigot-api",
          "version": {
            "requires": "1.21.4-R0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "BaseProviders-2.21.0.jar",
          "url": "BaseProviders-2.21.0.jar",
          "size": 41238,
          "sha512": "d4f6154cdbe10f4683d5f7f5cea5f2a0c1990bbcb0eb69fb54523added81755b319e3e6734e930044824bbe585ee46517675b51d213879c030ab7d59421019e5",
          "sha256": "431c006161b61a4fc1b93954abc6d4d9058ffae48a79ddc19ca49d59f8b0c5aa",
          "sha1": "1d9cc7056347bc3b1118767bae4bacf0e1f4fc37",
          "md5": "8f3cd09b13c2a55ffabe9418c99a3383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spigotmc",
          "module": "spigot-api",
          "version": {
            "requires": "1.21.4-R0.1-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          },
          "reason": "Bukkit API ships old versions, Configurate requires modern versions"
        }
      ],
      "files": [
        {
          "name": "BaseProviders-2.21.0.jar",
          "url": "BaseProviders-2.21.0.jar",
          "size": 41238,
          "sha512": "d4f6154cdbe10f4683d5f7f5cea5f2a0c1990bbcb0eb69fb54523added81755b319e3e6734e930044824bbe585ee46517675b51d213879c030ab7d59421019e5",
          "sha256": "431c006161b61a4fc1b93954abc6d4d9058ffae48a79ddc19ca49d59f8b0c5aa",
          "sha1": "1d9cc7056347bc3b1118767bae4bacf0e1f4fc37",
          "md5": "8f3cd09b13c2a55ffabe9418c99a3383"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BaseProviders-2.21.0-javadoc.jar",
          "url": "BaseProviders-2.21.0-javadoc.jar",
          "size": 242580,
          "sha512": "0669d43a184f4c15c39e8600838f2e4fcd7899e7da4a5822a3b4c9fe6850a5b65ecd7ec1f6d5d8d7c51bcc9bae5c0fee28968003b0a9619696f1276efcaa3def",
          "sha256": "f01bbe60a511fa616486656809ed571085c57e4c06079e550d6a170ea9748871",
          "sha1": "bf48d96a81ec758a3a56a735d8bd2b50c6a8c4f5",
          "md5": "4436e99dd912825b4a373e831b859ac7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BaseProviders-2.21.0-sources.jar",
          "url": "BaseProviders-2.21.0-sources.jar",
          "size": 25616,
          "sha512": "e7132f9d73b9574fe51d8af3f7ac2a24c2b25c3d6559b025173125e1611d36b9a8e98819d29bd4499cdd1690c5f157dd0dd5db8326dde5773b5727bf57c3abae",
          "sha256": "3d10e3640e7a3bc3778f1d9b3e8d05d70006d5c3ac313ce068265fabb146b759",
          "sha1": "7c1c079bf6dc5c9e5e131a25c8ad324b20b2341c",
          "md5": "e6bd65f0f267d4787f413f3fcabb0bdc"
        }
      ]
    }
  ]
}
