{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-gson",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.24.0.jar",
          "url": "adventure-text-serializer-gson-4.24.0.jar",
          "size": 62103,
          "sha512": "f84f4006f6d38d486ea29e43e1bae3054508993545424e1b288c64d2a9ab1b4297f785e2580137893c2eb645bdc18758ece8ebfcdb66d6131ed389d04fbee563",
          "sha256": "2414c3ce5ffe1b7e31de86968ebd3e9f2a50e354939b276588ed2cd64c431821",
          "sha1": "23ef45e010ac5f4be65d114f14d621669cee6fca",
          "md5": "3c91340e5cf06184245a162a56458356"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-commons",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.24.0.jar",
          "url": "adventure-text-serializer-gson-4.24.0.jar",
          "size": 62103,
          "sha512": "f84f4006f6d38d486ea29e43e1bae3054508993545424e1b288c64d2a9ab1b4297f785e2580137893c2eb645bdc18758ece8ebfcdb66d6131ed389d04fbee563",
          "sha256": "2414c3ce5ffe1b7e31de86968ebd3e9f2a50e354939b276588ed2cd64c431821",
          "sha1": "23ef45e010ac5f4be65d114f14d621669cee6fca",
          "md5": "3c91340e5cf06184245a162a56458356"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.24.0-javadoc.jar",
          "url": "adventure-text-serializer-gson-4.24.0-javadoc.jar",
          "size": 108770,
          "sha512": "5bbbffda2233b7257475fac79a4793b2f848738e11c5bd772efcae04346cabb1db0b96897415fe6233a32388432d2fcfbf7ce84fd020792c38432702495bc8ae",
          "sha256": "604684638389da0911d764c69d7323b200c51111f13ec33d6789d14ebc573c3b",
          "sha1": "0f88c73016ef07b87eba152a645d6155c037f34b",
          "md5": "f7efc7bb3b0caeee2c943cf9fb971a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-gson-4.24.0-sources.jar",
          "url": "adventure-text-serializer-gson-4.24.0-sources.jar",
          "size": 44761,
          "sha512": "bd3959e40712078e95e517c30b469d8a1f8f2109cbe61adaf263259e725bfb1a770699aafd9803a905dd18f8a7e43eaf30979549fef8980ab45f52af486eb8cc",
          "sha256": "0a343a3d6180ed8c9ce54dc5c0410734e3d48eb8feff1d125138fd61c2dcec22",
          "sha1": "011300100fabada5e2ae3dec0be54fe2e141760d",
          "md5": "8024d080f376ddd393dcbe77ac1f978a"
        }
      ]
    }
  ]
}
