{
  "formatVersion": "1.1",
  "component": {
    "group": "net.essentialsx",
    "module": "EssentialsX",
    "version": "2.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.papermc",
          "module": "paperlib",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.essentialsx",
          "module": "BaseProviders",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "net.essentialsx",
          "module": "PaperProvider",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "net.essentialsx",
          "module": "NMSReflectionProvider",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.bukkit",
              "module": "bukkit"
            }
          ]
        },
        {
          "group": "net.essentialsx",
          "module": "1_8Provider",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.spigotmc",
              "module": "spigot"
            }
          ]
        },
        {
          "group": "net.essentialsx",
          "module": "1_12Provider",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.bukkit",
              "module": "bukkit"
            }
          ]
        },
        {
          "group": "org.spigotmc",
          "module": "spigot-api",
          "version": {
            "requires": "1.21.4-R0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "EssentialsX-2.21.0-unshaded.jar",
          "url": "EssentialsX-2.21.0-unshaded.jar",
          "size": 2195079,
          "sha512": "5d8fe1da90bb29db2baff85b139d38355af824dfe08041fccdbd9b57a3a66d22c78bad614188062f17a8baaed480486afe0afdb87f039936b62d2bb8ebc068bf",
          "sha256": "de2033cac72e14e4840714666a4f720cda9874cbcc5199070f6cd7dff2e26e25",
          "sha1": "8692dcfab2a4ae211e261aaab87e0e9c9bb45ffb",
          "md5": "e3968bbeeef987c88bf1671f1d0588ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.0"
          }
        },
        {
          "group": "nu.studer",
          "module": "java-ordered-properties",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-bukkit",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "org.bstats",
          "module": "bstats-bukkit",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.papermc",
          "module": "paperlib",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.essentialsx",
          "module": "BaseProviders",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "net.essentialsx",
          "module": "PaperProvider",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "net.essentialsx",
          "module": "NMSReflectionProvider",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.bukkit",
              "module": "bukkit"
            }
          ]
        },
        {
          "group": "net.essentialsx",
          "module": "1_8Provider",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.spigotmc",
              "module": "spigot"
            }
          ]
        },
        {
          "group": "net.essentialsx",
          "module": "1_12Provider",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.bukkit",
              "module": "bukkit"
            }
          ]
        },
        {
          "group": "org.spigotmc",
          "module": "spigot-api",
          "version": {
            "requires": "1.21.4-R0.1-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          },
          "reason": "Bukkit API ships old versions, Configurate requires modern versions"
        }
      ],
      "files": [
        {
          "name": "EssentialsX-2.21.0-unshaded.jar",
          "url": "EssentialsX-2.21.0-unshaded.jar",
          "size": 2195079,
          "sha512": "5d8fe1da90bb29db2baff85b139d38355af824dfe08041fccdbd9b57a3a66d22c78bad614188062f17a8baaed480486afe0afdb87f039936b62d2bb8ebc068bf",
          "sha256": "de2033cac72e14e4840714666a4f720cda9874cbcc5199070f6cd7dff2e26e25",
          "sha1": "8692dcfab2a4ae211e261aaab87e0e9c9bb45ffb",
          "md5": "e3968bbeeef987c88bf1671f1d0588ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EssentialsX-2.21.0-javadoc.jar",
          "url": "EssentialsX-2.21.0-javadoc.jar",
          "size": 1804510,
          "sha512": "40175d609b484cd016766e5c05b612e4386c294d23d94cac8b5c60adb63e0f9944e4524ba708bb3aabd4922b9ac669717d2f2b1ca92d73862ca9e7502b64bcd0",
          "sha256": "c8e287e3ef4dab44ca69aec058e269e27538f071e4cf24ebd7c631eca287521c",
          "sha1": "5a68e4c586f3df462fae9daeb372e8bc9cd33ab4",
          "md5": "b3cc6b8a7ccd0228e72a2bfa46072e72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EssentialsX-2.21.0-sources.jar",
          "url": "EssentialsX-2.21.0-sources.jar",
          "size": 1615153,
          "sha512": "08a6928b9bc35e95842b992808ade7424f06eb76590077fceda1fe8658310febfe6977201e80f449c31b9e08771f863d5db52476ce481d3fd737dcfa73ae42f5",
          "sha256": "928e5d8a84f1280cdd962c54026fcf308485f59b6280bce8b921e950dcf7e0f0",
          "sha1": "e601c230510c3a8da6316b2f77edd6d52d289df8",
          "md5": "5b45810ca07a6beb6d308d1e22e4bd4d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EssentialsX-2.21.0.jar",
          "url": "EssentialsX-2.21.0.jar",
          "size": 4605977,
          "sha512": "b9ebac202a129cda3bcdce4c553519425d0aad55ef585b5197367cc868d3a80ee6917b9069cff0f320b1e6daf5699ef3b5a395e23b19ce453d7ac502c4e8b34f",
          "sha256": "5704322a54836b984b110f7e2208baed1886c2efed4446b497e67e512fec90c5",
          "sha1": "fc71f668dba90040e63992361793ba73941b810e",
          "md5": "a4de9003948519909816e1684bcf7439"
        }
      ]
    }
  ]
}
