{
  "formatVersion": "1.1",
  "component": {
    "group": "io.papermc",
    "module": "paperlib",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "cehnrqcqlzhx5n4yl4gcepdhum"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "paperlib-1.0.6.jar",
          "url": "paperlib-1.0.6.jar",
          "size": 22947,
          "sha512": "813d49dc5157bca41859c1edef93f47315781e65190e909b4f8f1e399578f97a21b00248b1aa2dbfab0f855ce821e46a27f0784fc809b317b98c415418ceab33",
          "sha256": "4f817e4506afc6175964e24da8cc9e425584042600054b737804372b0936d327",
          "sha1": "183e180c464abbe85c01ae200f33d3938136fef1",
          "md5": "293d1942781eedafe6bc3b39ec138e6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paperlib-1.0.6.jar",
          "url": "paperlib-1.0.6.jar",
          "size": 22947,
          "sha512": "813d49dc5157bca41859c1edef93f47315781e65190e909b4f8f1e399578f97a21b00248b1aa2dbfab0f855ce821e46a27f0784fc809b317b98c415418ceab33",
          "sha256": "4f817e4506afc6175964e24da8cc9e425584042600054b737804372b0936d327",
          "sha1": "183e180c464abbe85c01ae200f33d3938136fef1",
          "md5": "293d1942781eedafe6bc3b39ec138e6d"
        }
      ]
    }
  ]
}
