{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-json-legacy-impl",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.21.0.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.21.0.jar",
          "size": 4985,
          "sha512": "8e19cd732c4d02fe5ea435630f8c42ebde49368f8acfe297f27e86341c3f2bb658a2890cb759b1ecefbc49983a96438452216d03a7caafaa9e1f198052181e47",
          "sha256": "ccc0ac5c8052a350bfcaba67ca4d37c7214be5a1f8d92caae38c1cad6cf8bf55",
          "sha1": "a92ba15e9243805f42de07078d09ed39d627b6c2",
          "md5": "62dd6b0f9f1dbb26ee66ff0c88ee7b73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.21.0.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.21.0.jar",
          "size": 4985,
          "sha512": "8e19cd732c4d02fe5ea435630f8c42ebde49368f8acfe297f27e86341c3f2bb658a2890cb759b1ecefbc49983a96438452216d03a7caafaa9e1f198052181e47",
          "sha256": "ccc0ac5c8052a350bfcaba67ca4d37c7214be5a1f8d92caae38c1cad6cf8bf55",
          "sha1": "a92ba15e9243805f42de07078d09ed39d627b6c2",
          "md5": "62dd6b0f9f1dbb26ee66ff0c88ee7b73"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.21.0-javadoc.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.21.0-javadoc.jar",
          "size": 82152,
          "sha512": "22cd9777f683543fab3c154d23a76251bf2105dbb5b0ad3cb3dff3c6b3e164e2041e4af131321982dc5a82c75b926cd43c76799afd355107008a8992eb73c485",
          "sha256": "23777d7e88312eeb4f2757db33c9d45f5cdf11f3a9ee05fe461493363c0dfc37",
          "sha1": "64c97d9a978d71a0430bad2db80b19be48481ef7",
          "md5": "5c7bd03efb0a924a912d67750a506ef0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.21.0-sources.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.21.0-sources.jar",
          "size": 5308,
          "sha512": "083f8081f6a6bdd3edb8fba7903359ba683e3474dfd6759b2fd8a974d877c2798766b034987556dca6f3b242ac46985c72f618731aee0c9c701b072f9c1a2b35",
          "sha256": "f205d0e6384a22df34884a5b73d911bc1c06b9262cf565dc2af1896751e2ce7e",
          "sha1": "b5ea9e0d29d79075298008bcec9475f5036b4546",
          "md5": "720774cf8f872271cf19ba6e17d2dd88"
        }
      ]
    }
  ]
}
