{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "8.3"
    }
  },
  "component" : {
    "group" : "com.github.oraxen",
    "module" : "oraxen",
    "version" : "1.162.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "oraxen-1.162.0.jar",
      "url" : "oraxen-1.162.0.jar",
      "size" : 2915208,
      "sha512" : "ec679dbfe5a3a56dcef88f7e9fcf76df7d2acc2a5c53f9e21f11f9612dd5172001fd4d19c4d3d79750193e55c63fa3e0cba16a924cba81347f6cbe5ac983306b",
      "sha256" : "66627d23c7d7cc1ef635c4ef228973078ba6310367b51a37b2103f90261fbb80",
      "sha1" : "49ed1134de936f1b15ff1f9d82d980fdff9978d7",
      "md5" : "dc33706e8c9f93848baa7a762bcfed8b"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.oraxen",
      "module" : "core",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_18_R1",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_18_R2",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_19_R1",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_19_R2",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_19_R3",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_20_R1",
      "version" : {
        "requires" : "1.162.0"
      }
    }, {
      "group" : "com.github.oraxen",
      "module" : "v1_20_R2",
      "version" : {
        "requires" : "1.162.0"
      }
    } ],
    "files" : [ {
      "name" : "oraxen-1.162.0.jar",
      "url" : "oraxen-1.162.0.jar",
      "size" : 2915208,
      "sha512" : "ec679dbfe5a3a56dcef88f7e9fcf76df7d2acc2a5c53f9e21f11f9612dd5172001fd4d19c4d3d79750193e55c63fa3e0cba16a924cba81347f6cbe5ac983306b",
      "sha256" : "66627d23c7d7cc1ef635c4ef228973078ba6310367b51a37b2103f90261fbb80",
      "sha1" : "49ed1134de936f1b15ff1f9d82d980fdff9978d7",
      "md5" : "dc33706e8c9f93848baa7a762bcfed8b"
    } ]
  }, {
    "name" : "shadowRuntimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "shadowed",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "oraxen-1.162.0.jar",
      "url" : "oraxen-1.162.0.jar",
      "size" : 2915208,
      "sha512" : "ec679dbfe5a3a56dcef88f7e9fcf76df7d2acc2a5c53f9e21f11f9612dd5172001fd4d19c4d3d79750193e55c63fa3e0cba16a924cba81347f6cbe5ac983306b",
      "sha256" : "66627d23c7d7cc1ef635c4ef228973078ba6310367b51a37b2103f90261fbb80",
      "sha1" : "49ed1134de936f1b15ff1f9d82d980fdff9978d7",
      "md5" : "dc33706e8c9f93848baa7a762bcfed8b"
    } ]
  } ]
}