{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-platform-bukkit",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-bungeecord",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "adventure-platform-bukkit-4.4.1.jar",
          "url": "adventure-platform-bukkit-4.4.1.jar",
          "size": 134005,
          "sha512": "b355f7193f397b631a26f3777e3c73e6886456c35b5cf74d9bfe205d028da9c2bd26da9e6bee3e15613ecfaffaf63c3d813943765cf26e9a6d9fff4407cc5320",
          "sha256": "cdcb3a66abbf9e393614db5deb27f841117c5b5b7ef52753a2c846fd46c9cdf1",
          "sha1": "07a86b8016918f0aba23d0c69adcd65f78824799",
          "md5": "480fc1c088f7a76a350e72a08aa09811"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson-legacy-impl",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-facet",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-viaversion",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-bungeecord",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "adventure-platform-bukkit-4.4.1.jar",
          "url": "adventure-platform-bukkit-4.4.1.jar",
          "size": 134005,
          "sha512": "b355f7193f397b631a26f3777e3c73e6886456c35b5cf74d9bfe205d028da9c2bd26da9e6bee3e15613ecfaffaf63c3d813943765cf26e9a6d9fff4407cc5320",
          "sha256": "cdcb3a66abbf9e393614db5deb27f841117c5b5b7ef52753a2c846fd46c9cdf1",
          "sha1": "07a86b8016918f0aba23d0c69adcd65f78824799",
          "md5": "480fc1c088f7a76a350e72a08aa09811"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-bungeecord",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "adventure-platform-bukkit-4.4.1-javadoc.jar",
          "url": "adventure-platform-bukkit-4.4.1-javadoc.jar",
          "size": 330681,
          "sha512": "83faf06b321cedf1bae3859eb6d5cda30e6650506b44cc5a38344471d586deecbaab270b12de679238489cef449981141bcb9dd3c0249a274462f1b6c10cfbaa",
          "sha256": "d091718f74e06e175da5b383295143f563ac3a23c33503486f17870d2a57ef9d",
          "sha1": "7c01a0a2419ada0632ea35783b41d53d430c70a1",
          "md5": "0b04afb67318abad0aa0adfb78adde2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-platform-bukkit-4.4.1-sources.jar",
          "url": "adventure-platform-bukkit-4.4.1-sources.jar",
          "size": 49485,
          "sha512": "41ef3baa3cf34145f0772c9db1e8e6271397524740fe99adbd5ceadb995b29aa8bbaaf5e5ff5f7d5bcdfc6f6f9cbbada8ecc52e7e1d9bc01069bf751b0f57e51",
          "sha256": "da941a33896e29ca13fa48dfd12a74642e36423d133973df7920c8cd569ad00f",
          "sha1": "77e8f83ec9fe6bd2efe45da28afe87c499acb503",
          "md5": "92e153e4d736088fe52a0639a2b185a6"
        }
      ]
    }
  ]
}
