{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "8.4"
    }
  },
  "component" : {
    "group" : "com.github.Exlll",
    "module" : "ConfigLib",
    "version" : "v4.5.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "com.github.Exlll.ConfigLib",
      "module" : "configlib-core",
      "version" : {
        "requires" : "v4.5.0"
      }
    } ],
    "files" : [ {
      "name" : "configlib-yaml-v4.5.0.jar",
      "url" : "configlib-yaml-v4.5.0.jar",
      "size" : 12748,
      "sha512" : "d59a4c6d8228cb3614d97e954c8a1c14441b0647500103b1b82fb512b34bace313b94ed552e07fd92b98299a940b12094965e765f784afc572fa04ae52f667b8",
      "sha256" : "43474643fd7125bf2675e1aefc42d931f5b78186840549f9c5e1d2f38626e60b",
      "sha1" : "5d22767b4e13dd50f38bddd8199ca2ae80a7b68e",
      "md5" : "52eb910d9728592f9736da6a9965d91b"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.snakeyaml",
      "module" : "snakeyaml-engine",
      "version" : {
        "requires" : "2.7"
      }
    }, {
      "group" : "com.github.Exlll.ConfigLib",
      "module" : "configlib-core",
      "version" : {
        "requires" : "v4.5.0"
      }
    } ],
    "files" : [ {
      "name" : "configlib-yaml-v4.5.0.jar",
      "url" : "configlib-yaml-v4.5.0.jar",
      "size" : 12748,
      "sha512" : "d59a4c6d8228cb3614d97e954c8a1c14441b0647500103b1b82fb512b34bace313b94ed552e07fd92b98299a940b12094965e765f784afc572fa04ae52f667b8",
      "sha256" : "43474643fd7125bf2675e1aefc42d931f5b78186840549f9c5e1d2f38626e60b",
      "sha1" : "5d22767b4e13dd50f38bddd8199ca2ae80a7b68e",
      "md5" : "52eb910d9728592f9736da6a9965d91b"
    } ]
  }, {
    "name" : "javadocElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "javadoc",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-yaml-v4.5.0.jar",
      "url" : "configlib-yaml-v4.5.0.jar",
      "size" : 87575,
      "sha512" : "86edd870e68dd6c8055548e71c570352877690a970e29335881b3dfc3333a549de83a7bd0684af1cdfbcb324b6b436d26be3f970fbbc1f5738e982af9f46ecf7",
      "sha256" : "8dc3d3f183b5bdb7a0316ae4dadd12e443d3833b52ec5daafce61bb26a585786",
      "sha1" : "6034d50da175f52b15b972c8244c46281d99a273",
      "md5" : "6044911cfb53c60b71bd62724d44830f"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-yaml-v4.5.0.jar",
      "url" : "configlib-yaml-v4.5.0.jar",
      "size" : 6662,
      "sha512" : "e9c652526c72c61ddeba10c8d36488f0796fadf782279898d8b476401fa69d7099dcdeb515a4ec31f5b630c21e546fde9efbaadb93b1fa7cdc760eb153ebac7b",
      "sha256" : "0416c1f859192b5ee502c5c279d2dd5e5c2982ada2ae57d7ed29d7a5ed5183d2",
      "sha1" : "f4c5173c6441f9893af5daba9df26497855c55f4",
      "md5" : "f91f97c7cfa89d2faad28b1809f3d90a"
    } ]
  } ]
}