{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-platform-bungeecord",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-bungeecord",
          "version": {
            "requires": "4.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-bungeecord-4.4.0.jar",
          "url": "adventure-platform-bungeecord-4.4.0.jar",
          "size": 30892,
          "sha512": "7ea92b784fb0ac2705e51cffc577db2f2fa2452ff06e05ed028f42001b545700a0356d96a23e9cb919c7b5ce389b840319a32dde7d200f8203f58b4a06bf9908",
          "sha256": "853e024d373e564ed062a363484737d9ad28789a48a0251e6bed7dd8c3da355a",
          "sha1": "f221be3345cc7bb964ae0253d60f5e156189383f",
          "md5": "7562ec01b4fc84c06c0b65309d8e0deb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-facet",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-bungeecord",
          "version": {
            "requires": "4.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-bungeecord-4.4.0.jar",
          "url": "adventure-platform-bungeecord-4.4.0.jar",
          "size": 30892,
          "sha512": "7ea92b784fb0ac2705e51cffc577db2f2fa2452ff06e05ed028f42001b545700a0356d96a23e9cb919c7b5ce389b840319a32dde7d200f8203f58b4a06bf9908",
          "sha256": "853e024d373e564ed062a363484737d9ad28789a48a0251e6bed7dd8c3da355a",
          "sha1": "f221be3345cc7bb964ae0253d60f5e156189383f",
          "md5": "7562ec01b4fc84c06c0b65309d8e0deb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-bungeecord",
          "version": {
            "requires": "4.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-bungeecord-4.4.0-javadoc.jar",
          "url": "adventure-platform-bungeecord-4.4.0-javadoc.jar",
          "size": 286166,
          "sha512": "c7384dea1a21c2a18640ddfe456b03af8fe0e8542ef5a7500440ea64080e86a8a6d12fcbf42dffcb67f283a0df415102b53a930701de2222063e39bcc34cf87a",
          "sha256": "57ae63b67834ae5f2e5f65f0573370eb449a21553de52ac494bcbf4e87c55b9d",
          "sha1": "de6f90ff9c9de3579fc64418e1e5be2b956e77af",
          "md5": "9c05974024250003db4bf53643b8b2f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-platform-bungeecord-4.4.0-sources.jar",
          "url": "adventure-platform-bungeecord-4.4.0-sources.jar",
          "size": 12890,
          "sha512": "59280d83a45a7df2d8ef63e3ff53f835e660fa955fda058289e4c5faa9a46fd972de0cab094f3a54a5474f0ed54867ed5b34d83ba36b4adfb2537409ffcb7ea7",
          "sha256": "da6188455a7ee1606bdbba8310642237f3a631186a94716079ca2b526f337615",
          "sha1": "3806194d0d1735ea74e7f5ab5124ff96cae39d6d",
          "md5": "8d4c78155dc781bdf274c551fce7d09a"
        }
      ]
    }
  ]
}
