{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-minimessage",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-minimessage-4.24.0.jar",
          "url": "adventure-text-minimessage-4.24.0.jar",
          "size": 186671,
          "sha512": "99e8b9bbf7138f096fc706449503f6d01e2538e7f8ad5cc068992f93d34e7f98dcc1f05594f4f8a7a119d1667953700549c897fadffe9fb20797d869100bed0a",
          "sha256": "7a7f44dc3b78379b918f91dce38bff26a0963bfe303a3fe16c91d30a5c5e23e5",
          "sha1": "64547cb2485d5fc8007aaf3bab0e75108745f1b6",
          "md5": "70a3270a9939780af8ccf1b8ef9b6667"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-minimessage-4.24.0.jar",
          "url": "adventure-text-minimessage-4.24.0.jar",
          "size": 186671,
          "sha512": "99e8b9bbf7138f096fc706449503f6d01e2538e7f8ad5cc068992f93d34e7f98dcc1f05594f4f8a7a119d1667953700549c897fadffe9fb20797d869100bed0a",
          "sha256": "7a7f44dc3b78379b918f91dce38bff26a0963bfe303a3fe16c91d30a5c5e23e5",
          "sha1": "64547cb2485d5fc8007aaf3bab0e75108745f1b6",
          "md5": "70a3270a9939780af8ccf1b8ef9b6667"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-minimessage-4.24.0-javadoc.jar",
          "url": "adventure-text-minimessage-4.24.0-javadoc.jar",
          "size": 194866,
          "sha512": "c2ee3bf044eafe6db75df89d24e758184df4d9a772865d412450cd9dd7860a9757239aff663002b15445cbb4ba526530d708c3dc844ff5821942e7ca5336593c",
          "sha256": "e0091b88cec9a0e01cfd9176d671e76e0a6178543b772be22e22c728605cd4bd",
          "sha1": "0bc67f85c7969198db9ac393b53701e64c0e4f55",
          "md5": "cf3bd3ebe8d8190fbce1cc695f1b01c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-minimessage-4.24.0-sources.jar",
          "url": "adventure-text-minimessage-4.24.0-sources.jar",
          "size": 165701,
          "sha512": "a06a37ad6d583b55f68d4f6449fbb023f1bfc7190a081546d0c0178cc000b881bdd852cbd8d027eae88d7498b1f87d57c12dcead941515110b309368524170f2",
          "sha256": "3233389f10df56fdfe84ff77b59bdd654c07362a32b4485fad151c4e2707dff1",
          "sha1": "56d0b06ef4fd0dd0e0370fd6fba31c52c65b4aa4",
          "md5": "9126cff72240a1275ccd7d82bae5eb7b"
        }
      ]
    }
  ]
}
