{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-nbt",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.24.0.jar",
          "url": "adventure-nbt-4.24.0.jar",
          "size": 104141,
          "sha512": "1e0e8f8dcbfff1341c911b990b170524f3aaabc0ca5c3349df125392a0576649f0cdafa706205abfbe88ed7509623019952730f6a50f51f716746b18e518ba00",
          "sha256": "8ffff89dbc7f0c1e4ccdf3337f90120e9a0fcff36cc4697d1e7769ff4bd56853",
          "sha1": "e49c10a024950bb5f40d37812a99427dd5328ec1",
          "md5": "29a272483ca0a96cc88358e61f416399"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.24.0.jar",
          "url": "adventure-nbt-4.24.0.jar",
          "size": 104141,
          "sha512": "1e0e8f8dcbfff1341c911b990b170524f3aaabc0ca5c3349df125392a0576649f0cdafa706205abfbe88ed7509623019952730f6a50f51f716746b18e518ba00",
          "sha256": "8ffff89dbc7f0c1e4ccdf3337f90120e9a0fcff36cc4697d1e7769ff4bd56853",
          "sha1": "e49c10a024950bb5f40d37812a99427dd5328ec1",
          "md5": "29a272483ca0a96cc88358e61f416399"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.24.0-javadoc.jar",
          "url": "adventure-nbt-4.24.0-javadoc.jar",
          "size": 187194,
          "sha512": "ae5c096ab996f39712cb1e538404c49e7e44415a2a645298d10c70d310bc4dd6e2406fcfe7b84fb68b06b53d95108fed312fd96add9e394c19a74ff4c7450105",
          "sha256": "523ad205dc0a75e2594f010fe83f49302761b5dd7b6461b1bf686c01f86b54a1",
          "sha1": "644305c18258188481c4db81cb1c31eccd4d2f1d",
          "md5": "37ae9c7d14b6010f63cb8533fbac5960"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-nbt-4.24.0-sources.jar",
          "url": "adventure-nbt-4.24.0-sources.jar",
          "size": 87363,
          "sha512": "37b57342f4051a5202ce1342aa4e2ddb927e1880be15dbbb1630e2e74d1f19366d1afb6f27b8f6f50b258ad3ef7674184244b442c11cadfe6d0de102b8191a89",
          "sha256": "fb860bdb772af8d2a62e4e475801c3ef05a7f7fff7306cdebd9784d06761cfbb",
          "sha1": "4353d90382a093d50eda9592b965f9278c5f0e82",
          "md5": "61190ef70fc27c6132389eb761afe02a"
        }
      ]
    }
  ]
}
