{
  "formatVersion": "1.1",
  "component": {
    "group": "net.essentialsx",
    "module": "1_12Provider",
    "version": "2.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.essentialsx",
          "module": "NMSReflectionProvider",
          "version": {
            "requires": "2.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "1_12Provider-2.21.0.jar",
          "url": "1_12Provider-2.21.0.jar",
          "size": 35752,
          "sha512": "2dc6b512603f8bc395742d2e24c815cf1ef39e9817db66f6046ddb03d4175b348ccb205146e5e3e662718aa856ffe38727d1c8ad0f7a01a1f898d31675ce198a",
          "sha256": "a981e9f513f812f4dcece7b5f99f6f23a11ebc626864efef72d9b726ee911eb4",
          "sha1": "960b38dba41e3a28116cb24b6ea42c50bf83bb4b",
          "md5": "3113cc6d404850520bff0fc74291d1e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.essentialsx",
          "module": "BaseProviders",
          "version": {
            "requires": "2.21.0"
          },
          "excludes": [
            {
              "group": "org.spigotmc",
              "module": "spigot-api"
            }
          ]
        },
        {
          "group": "net.essentialsx",
          "module": "NMSReflectionProvider",
          "version": {
            "requires": "2.21.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          },
          "reason": "Bukkit API ships old versions, Configurate requires modern versions"
        }
      ],
      "files": [
        {
          "name": "1_12Provider-2.21.0.jar",
          "url": "1_12Provider-2.21.0.jar",
          "size": 35752,
          "sha512": "2dc6b512603f8bc395742d2e24c815cf1ef39e9817db66f6046ddb03d4175b348ccb205146e5e3e662718aa856ffe38727d1c8ad0f7a01a1f898d31675ce198a",
          "sha256": "a981e9f513f812f4dcece7b5f99f6f23a11ebc626864efef72d9b726ee911eb4",
          "sha1": "960b38dba41e3a28116cb24b6ea42c50bf83bb4b",
          "md5": "3113cc6d404850520bff0fc74291d1e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1_12Provider-2.21.0-javadoc.jar",
          "url": "1_12Provider-2.21.0-javadoc.jar",
          "size": 168432,
          "sha512": "862dee4cc0b79584f2b31ee80188e608599f344e22515f990ca14710548ecfbf322c6604ed8e95532a81c1454776b63dfdd0567079b2b21e2228ae3efaeaec30",
          "sha256": "d17b0e584b4d59894e0acda2df7e83b64c846a63f3ac1bae6793a5a95cc9f266",
          "sha1": "48cec4963780024ea74972987700b319101a8b17",
          "md5": "bb23b0c9a72ad0fa19f54b4b667caac9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1_12Provider-2.21.0-sources.jar",
          "url": "1_12Provider-2.21.0-sources.jar",
          "size": 15580,
          "sha512": "603702e2df0685c187ab2b6d91202e65ca3e2931907ae20ed426113c287a3aa9e98a59ece09a87062cc867e56283a2e801f29742a87dd63c66c885df55ddce64",
          "sha256": "650d91fdbb393e0ae3783d9fb96e0f9bc95adc0309e05e13af748563f5138f80",
          "sha1": "bc40bd6d0d5f0c1a8adbb06a6607349e93d771bb",
          "md5": "31918d246a9fe0e850cdd941e2912c86"
        }
      ]
    }
  ]
}
