{
  "formatVersion": "1.1",
  "component": {
    "group": "club.minnced",
    "module": "opus-java-api",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opus-java-api-1.1.1.jar",
          "url": "opus-java-api-1.1.1.jar",
          "size": 11061,
          "sha512": "5cbfe4d570cfa382824840f5cfbeb2439e2dbf5f34a0a151edf474e4adbcc3c26b5025347546b08b30c726100dae1ad0a9aed94ce3199de55967cf8a9c6939da",
          "sha256": "7cd818482722cd2809b14aaed1856f084838f90493b69d1b819868c778466cfb",
          "sha1": "63c6910fb1f7eebbfd922a01d37a4b94fa0ee5e3",
          "md5": "ea6c7917563db24e91b4358afb20ee0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "4.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "opus-java-api-1.1.1.jar",
          "url": "opus-java-api-1.1.1.jar",
          "size": 11061,
          "sha512": "5cbfe4d570cfa382824840f5cfbeb2439e2dbf5f34a0a151edf474e4adbcc3c26b5025347546b08b30c726100dae1ad0a9aed94ce3199de55967cf8a9c6939da",
          "sha256": "7cd818482722cd2809b14aaed1856f084838f90493b69d1b819868c778466cfb",
          "sha1": "63c6910fb1f7eebbfd922a01d37a4b94fa0ee5e3",
          "md5": "ea6c7917563db24e91b4358afb20ee0c"
        }
      ]
    }
  ]
}
