{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-key",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.21.0.jar",
          "url": "adventure-key-4.21.0.jar",
          "size": 11239,
          "sha512": "9a173fd7e0c01f9f4bd6795405708e86c866c90ede2f7e62f3b5c64b9440a673684dbc6fb52b74af7aeb9d991966152846c72f8a2ac531d822bddfc51153f514",
          "sha256": "6a9398c9d402089f9da060a56b45cae7d58cbf199371a6d8ec1a26d8f94cc6bb",
          "sha1": "23b0079f459af5cb25923ee423fccbb8f894ccda",
          "md5": "66c58894901a9777b8a9ae856b7dd4c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.21.0.jar",
          "url": "adventure-key-4.21.0.jar",
          "size": 11239,
          "sha512": "9a173fd7e0c01f9f4bd6795405708e86c866c90ede2f7e62f3b5c64b9440a673684dbc6fb52b74af7aeb9d991966152846c72f8a2ac531d822bddfc51153f514",
          "sha256": "6a9398c9d402089f9da060a56b45cae7d58cbf199371a6d8ec1a26d8f94cc6bb",
          "sha1": "23b0079f459af5cb25923ee423fccbb8f894ccda",
          "md5": "66c58894901a9777b8a9ae856b7dd4c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.21.0-javadoc.jar",
          "url": "adventure-key-4.21.0-javadoc.jar",
          "size": 106559,
          "sha512": "e9d7f057591ec600ab3ef87de6fd8b9cdaf80d2d8cda87a43b28252f5a5597513850f42fb4509eb5ed3518def17c5fc8c487a9eb6b33e79efbf6a726efdf84ad",
          "sha256": "29f4a2dc7acb3a0a90bf54cb9806f940dee669ae149fef36899050d761eb33b4",
          "sha1": "fe4267ae60f159b458979a1a525ece2156e17f6d",
          "md5": "0506ddaea384858976706cefcfda2e9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-key-4.21.0-sources.jar",
          "url": "adventure-key-4.21.0-sources.jar",
          "size": 13329,
          "sha512": "701cb3f6465214f15daa378af145c56e7fcf6875c5c59689364c2982877366256819b2238716583a8f8aeed6144cab2d75ef8a010ee14b52e157925e8613f5c3",
          "sha256": "75ed7c8b0a4ef3439a2504cccdc25363510661c1f964c13a74c048ce3a7ffd56",
          "sha1": "c39ed581704884262c8bc9d463abbec38176adb3",
          "md5": "c3f2e438750e1cad7498d4198e038523"
        }
      ]
    }
  ]
}
