{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-bom",
    "version": "4.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-extra-kotlin",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-serializer-configurate3",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-serializer-configurate4",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson-legacy-impl",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.9.3"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-extra-kotlin",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-serializer-configurate3",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-serializer-configurate4",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson-legacy-impl",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.9.3"
          }
        }
      ]
    }
  ]
}
