{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-platform-api",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-api-4.4.1.jar",
          "url": "adventure-platform-api-4.4.1.jar",
          "size": 2528,
          "sha512": "3dd224a98667c0e80a32bb501bd2a2646ec7dcdfabf4dc8151ba1a7cf571ef0a0ac977437bc2ec9aab1585f45628f5118332a37e22e1119daecf18681ab472b8",
          "sha256": "ec604628c2b7c165ea74c1fcb3a2d0f03359c2c77a14960e3a0bc2e379670ac2",
          "sha1": "50847f49cb181fdafd0de37459bbe0fb8b1eb972",
          "md5": "44db3caceefbd9daa37625afb2ea8a5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-api-4.4.1.jar",
          "url": "adventure-platform-api-4.4.1.jar",
          "size": 2528,
          "sha512": "3dd224a98667c0e80a32bb501bd2a2646ec7dcdfabf4dc8151ba1a7cf571ef0a0ac977437bc2ec9aab1585f45628f5118332a37e22e1119daecf18681ab472b8",
          "sha256": "ec604628c2b7c165ea74c1fcb3a2d0f03359c2c77a14960e3a0bc2e379670ac2",
          "sha1": "50847f49cb181fdafd0de37459bbe0fb8b1eb972",
          "md5": "44db3caceefbd9daa37625afb2ea8a5d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-api-4.4.1-javadoc.jar",
          "url": "adventure-platform-api-4.4.1-javadoc.jar",
          "size": 311819,
          "sha512": "17f4c40756f04c0d710109f5d3d79189b776711c57986ed1f6a8bde76b14ada4d04c55ce413e528ed4873c159493f35bdfa6b2d60e4fabe46c07e5ccb3c6ffca",
          "sha256": "b08aaad169e923917359d8a07fb775553b41c511d4e74522c98fee75f38b28a4",
          "sha1": "1927d77b41190cbf473d608a542825c43113017e",
          "md5": "7f1b375310ca31bfb73b3cad5046cc26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-platform-api-4.4.1-sources.jar",
          "url": "adventure-platform-api-4.4.1-sources.jar",
          "size": 4166,
          "sha512": "6af172e8cad01dfbd29924392ce5fb5e2bb4f08d6712b1bfa36beae5d4e49ece3b8112d88f2942bce229b374e2756304f297095e3ddd3ba484ed07ae30c1894b",
          "sha256": "0781fc449d64bd3ff11701b7a0b84d823e37df85a6479704cc0f991b71f633d1",
          "sha1": "386bf1cb1bb877f11265534c10b3404b7a910793",
          "md5": "3174d45be044261d62119aec80d55e3f"
        }
      ]
    }
  ]
}
