{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mockbukkit.mockbukkit",
    "module": "mockbukkit-v1.21",
    "version": "4.72.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.papermc.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.21.8-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockbukkit-v1.21-4.72.8.jar",
          "url": "mockbukkit-v1.21-4.72.8.jar",
          "size": 1600486,
          "sha512": "9216a8883f7ebe5a46cb031a2c89acda0a3589775ee3f73c41bf0c17c52760ce383fa59a68e51f3bcd7c20b5fe53af55690f1606bb35971339b85f0b8ea7a4d9",
          "sha256": "66c98f9e3f7196f98935dd5a9e7baab4084064e015ff4e2079b2963270bce4c0",
          "sha1": "8e6d221ff182fa71c1fd87bf445153c41379b3b1",
          "md5": "3c19d2fc6cbd63191b77195019860722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-bungeecord",
          "version": {
            "requires": "4.4.0"
          },
          "excludes": [
            {
              "group": "net.kyori",
              "module": "adventure-api"
            },
            {
              "group": "net.kyori",
              "module": "adventure-platform-api"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "io.papermc.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.21.8-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockbukkit-v1.21-4.72.8.jar",
          "url": "mockbukkit-v1.21-4.72.8.jar",
          "size": 1600486,
          "sha512": "9216a8883f7ebe5a46cb031a2c89acda0a3589775ee3f73c41bf0c17c52760ce383fa59a68e51f3bcd7c20b5fe53af55690f1606bb35971339b85f0b8ea7a4d9",
          "sha256": "66c98f9e3f7196f98935dd5a9e7baab4084064e015ff4e2079b2963270bce4c0",
          "sha1": "8e6d221ff182fa71c1fd87bf445153c41379b3b1",
          "md5": "3c19d2fc6cbd63191b77195019860722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mockbukkit-v1.21-4.72.8-sources.jar",
          "url": "mockbukkit-v1.21-4.72.8-sources.jar",
          "size": 1077433,
          "sha512": "c974899b96d032d8a4fa9ba20081758e0c3950e30987cab3c4edd9c1e0cc78e674e977938d62808b7762a3e17ab15b80a91cf1674ecbca86658e4afc206161ff",
          "sha256": "4935940002d36a3836a43c4a4afc0d008b6760deb6a23127bd5637c4f6c41464",
          "sha1": "0380e13e2d7318c970cf04dc629477bae9ed3ac6",
          "md5": "e3ae1c91e37cebe2d57771b0afb5557c"
        }
      ]
    }
  ]
}
