{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-gson-legacy-impl",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json-legacy-impl",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-legacy-impl-4.21.0.jar",
          "url": "adventure-text-serializer-gson-legacy-impl-4.21.0.jar",
          "size": 3414,
          "sha512": "48f69bf42ee6447f2af0b1b119c6b583702aaee8ebed11295552edbb669640d7a2983597d7c18df257d4e83eac8333352d5990a609f1ffd4cd6bcaa819d6f590",
          "sha256": "682f5c59d853f24a40eb89afe4b92b83aa7f67cc85feb4d281c1b42e55b29f30",
          "sha1": "1400005b0f24905d1990e7fa7f25a209b4001f45",
          "md5": "6e5643364c83c783332177e36a1ff47f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json-legacy-impl",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-legacy-impl-4.21.0.jar",
          "url": "adventure-text-serializer-gson-legacy-impl-4.21.0.jar",
          "size": 3414,
          "sha512": "48f69bf42ee6447f2af0b1b119c6b583702aaee8ebed11295552edbb669640d7a2983597d7c18df257d4e83eac8333352d5990a609f1ffd4cd6bcaa819d6f590",
          "sha256": "682f5c59d853f24a40eb89afe4b92b83aa7f67cc85feb4d281c1b42e55b29f30",
          "sha1": "1400005b0f24905d1990e7fa7f25a209b4001f45",
          "md5": "6e5643364c83c783332177e36a1ff47f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json-legacy-impl",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-gson-legacy-impl-4.21.0-javadoc.jar",
          "url": "adventure-text-serializer-gson-legacy-impl-4.21.0-javadoc.jar",
          "size": 84531,
          "sha512": "a62414e1887b6fe266ccb26cd3c0d682dbb0dbc112e8af936b61994ff0c183ec962433201d2a15aee99d506e2328090e7f7cb21206b4cceac614b5798996828c",
          "sha256": "b9defc99d47924ffd4c90ff9528d8e7cdd187c9b4d6b38b1f63a9346fde35d4a",
          "sha1": "99bfc3e2bd83b8f18524fb481abe3298878d5b69",
          "md5": "68bbf632ceb62da2c21d527ffc733c82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-gson-legacy-impl-4.21.0-sources.jar",
          "url": "adventure-text-serializer-gson-legacy-impl-4.21.0-sources.jar",
          "size": 4785,
          "sha512": "d141feec222894d7423b159d454d31a83231cfc2b537f3210e4d9c3d6463386c2c8e5d16725a16d85531f8fcbc7ba4a8e793459a6a005ed2dbe6105c957e6215",
          "sha256": "259d798285495f423f3b73de167d82e841c4759887d2b966bf5d9f1e17ffbace",
          "sha1": "91c8ada9b905c8497ea57ba2ce69cb6e4cff1a95",
          "md5": "d97cf2f0400c3ecfa2da85ef77a47037"
        }
      ]
    }
  ]
}
