{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-json-legacy-impl",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.24.0.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.24.0.jar",
          "size": 4974,
          "sha512": "172216d853470181316ff1a28cb2cffd96395096f13204e4c0e4872f882da7d502de4a47d7424f28690ae7239e75934c9426aa5cf3544b775054c4a233e0b4e5",
          "sha256": "1de3bbd56c7a07ef8734d5d089828d654203a1fc198b3efca1d2bb6ac0c376c4",
          "sha1": "602c13674b7cb39143e26c97df0aed658efb8744",
          "md5": "719360beae2f93a7d36e5c1a02215c1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.24.0.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.24.0.jar",
          "size": 4974,
          "sha512": "172216d853470181316ff1a28cb2cffd96395096f13204e4c0e4872f882da7d502de4a47d7424f28690ae7239e75934c9426aa5cf3544b775054c4a233e0b4e5",
          "sha256": "1de3bbd56c7a07ef8734d5d089828d654203a1fc198b3efca1d2bb6ac0c376c4",
          "sha1": "602c13674b7cb39143e26c97df0aed658efb8744",
          "md5": "719360beae2f93a7d36e5c1a02215c1b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-json",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.24.0-javadoc.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.24.0-javadoc.jar",
          "size": 81266,
          "sha512": "ff8c215eb9d5f34546315f5d8ac02599c286ea6230061482ea03651ae84824ce9afe5f4750f74b72d689f7613fbfb15899b5da4b7bf7a5f6a3e23987a72c2093",
          "sha256": "c96aa13b5aa45279adc603065507f13d8666dc81c11b9bfde4f6bf333fab65b7",
          "sha1": "36e65627b03a5fc3e54bcaec75d94f2d9bf85061",
          "md5": "05823ced29ff2ee1b78fcd80a828e5e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-json-legacy-impl-4.24.0-sources.jar",
          "url": "adventure-text-serializer-json-legacy-impl-4.24.0-sources.jar",
          "size": 5308,
          "sha512": "083f8081f6a6bdd3edb8fba7903359ba683e3474dfd6759b2fd8a974d877c2798766b034987556dca6f3b242ac46985c72f618731aee0c9c701b072f9c1a2b35",
          "sha256": "f205d0e6384a22df34884a5b73d911bc1c06b9262cf565dc2af1896751e2ce7e",
          "sha1": "b5ea9e0d29d79075298008bcec9475f5036b4546",
          "md5": "720774cf8f872271cf19ba6e17d2dd88"
        }
      ]
    }
  ]
}
