{
  "formatVersion": "1.1",
  "component": {
    "group": "club.minnced",
    "module": "opus-java-natives",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opus-java-natives-1.1.1.jar",
          "url": "opus-java-natives-1.1.1.jar",
          "size": 2281442,
          "sha512": "41d002580dead92cef9ad6358896fb3cf2215f5113630151b1ee9bd972a009a163e527554fb735d77f01dab2bf90ac2e2a39416ecc42a6b31786a013bf78efcf",
          "sha256": "d38fa7629a8705b89a9fc266209224147f0efdfbf9be8e5a688583cf2175f5c3",
          "sha1": "183af66d80cd508bbf45343f30ee280e0750f416",
          "md5": "c12a536be2288d2b11b880fd0c56ac02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opus-java-natives-1.1.1.jar",
          "url": "opus-java-natives-1.1.1.jar",
          "size": 2281442,
          "sha512": "41d002580dead92cef9ad6358896fb3cf2215f5113630151b1ee9bd972a009a163e527554fb735d77f01dab2bf90ac2e2a39416ecc42a6b31786a013bf78efcf",
          "sha256": "d38fa7629a8705b89a9fc266209224147f0efdfbf9be8e5a688583cf2175f5c3",
          "sha1": "183af66d80cd508bbf45343f30ee280e0750f416",
          "md5": "c12a536be2288d2b11b880fd0c56ac02"
        }
      ]
    }
  ]
}
