{
  "formatVersion": "1.1",
  "component": {
    "group": "net.dv8tion",
    "module": "JDA",
    "version": "5.0.0-beta.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "club.minnced",
          "module": "opus-java",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        }
      ],
      "files": [
        {
          "name": "JDA-5.0.0-beta.16.jar",
          "url": "JDA-5.0.0-beta.16.jar",
          "size": 2063266,
          "sha512": "464ddd95d27ed17e58c8c7ee07c208e837865789bc609bf60f82adce465142dbc8d1455e80ddf54ace2f0f9231adbb69657183af907b0d18d75cf105947e4bc6",
          "sha256": "a12ef0505dd76236bc10ee98f2310e97850a0805b6af01fe96c60e9100cf99b0",
          "sha1": "5feedcaeb2cb1138dac914fb3afd7de00bfa4c2b",
          "md5": "86455628cf5da6de81a8ca4cef9b30a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.trove4j",
          "module": "trove4j",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "club.minnced",
          "module": "opus-java",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        }
      ],
      "files": [
        {
          "name": "JDA-5.0.0-beta.16.jar",
          "url": "JDA-5.0.0-beta.16.jar",
          "size": 2063266,
          "sha512": "464ddd95d27ed17e58c8c7ee07c208e837865789bc609bf60f82adce465142dbc8d1455e80ddf54ace2f0f9231adbb69657183af907b0d18d75cf105947e4bc6",
          "sha256": "a12ef0505dd76236bc10ee98f2310e97850a0805b6af01fe96c60e9100cf99b0",
          "sha1": "5feedcaeb2cb1138dac914fb3afd7de00bfa4c2b",
          "md5": "86455628cf5da6de81a8ca4cef9b30a8"
        }
      ]
    }
  ]
}
