{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.13.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.3"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.13.3.jar",
          "url": "junit-jupiter-params-5.13.3.jar",
          "size": 660954,
          "sha512": "b2e6aa28d29be942c05b3e0320ea37dd65eb56ab26d7b2f04427b3d19ced2836196a8db6d572c989f85f882fc0a0f4f0848571b356f0786d7ccb55fa20f469e0",
          "sha256": "df89bce8292c44fd3342564aeb5e8e9f45e6474e2b341e893ce8ff186089a51c",
          "sha1": "efda181a4e7df1ab0ed1fd24c2d7e252378f215f",
          "md5": "1805158d5f310fd6311f2d4fd9f685db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.13.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.3"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.13.3.jar",
          "url": "junit-jupiter-params-5.13.3.jar",
          "size": 660954,
          "sha512": "b2e6aa28d29be942c05b3e0320ea37dd65eb56ab26d7b2f04427b3d19ced2836196a8db6d572c989f85f882fc0a0f4f0848571b356f0786d7ccb55fa20f469e0",
          "sha256": "df89bce8292c44fd3342564aeb5e8e9f45e6474e2b341e893ce8ff186089a51c",
          "sha1": "efda181a4e7df1ab0ed1fd24c2d7e252378f215f",
          "md5": "1805158d5f310fd6311f2d4fd9f685db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.13.3-javadoc.jar",
          "url": "junit-jupiter-params-5.13.3-javadoc.jar",
          "size": 400800,
          "sha512": "b7a435a22fbfbb60884d9cf7d3e854dfa984b3f88f1e34f0036352e6f1188581c3c15a2d3e8b53f250f98073d142591bf9f43238cd68b3133127adbae0210913",
          "sha256": "f2d6bdaf925014ad525d7f04cc6be4494e1a3f2f5d73a0ebdbf86a1db6cf53f4",
          "sha1": "aa6f7a64348af20f2a7f1e5c507e6deadb94ce3d",
          "md5": "51a110b24d3c4e65fd704ee64f6b8fbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.13.3-sources.jar",
          "url": "junit-jupiter-params-5.13.3-sources.jar",
          "size": 132372,
          "sha512": "21195c51bcf4867c936845e1c75640c29e1b64ec303a0b0d49232497da1f397bb315a0f00daea7c5b2b03fecb082a19b3fd4f3e9d720d9bcb0c32ca866b58055",
          "sha256": "173be0fd56d5befb60e4ee812eb3e1faea05181ec948299661592222aef0e352",
          "sha1": "c34ec2635caea535e60d0ff50557919a023ea3b6",
          "md5": "694c033b22433beb6c8afd94f7726174"
        }
      ]
    }
  ]
}
