{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-commons",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.21.0.jar",
          "url": "adventure-text-serializer-commons-4.21.0.jar",
          "size": 2579,
          "sha512": "d71faefe501aed963a723975a9668fdfc7273821a792edafd811304de69587ed8715ff56839f1f54ff55bb7f045ce1e286008fd6b5e4848d9c857c251282a8c5",
          "sha256": "2eeb26605c723a57e5b63d24c2dd64182153a1486ca8e9f30bcba42d207f2c2a",
          "sha1": "5db2daa44fb995d19931b0c906fe20504752d9ec",
          "md5": "a843d789347c24749400166dd9fc9531"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.21.0.jar",
          "url": "adventure-text-serializer-commons-4.21.0.jar",
          "size": 2579,
          "sha512": "d71faefe501aed963a723975a9668fdfc7273821a792edafd811304de69587ed8715ff56839f1f54ff55bb7f045ce1e286008fd6b5e4848d9c857c251282a8c5",
          "sha256": "2eeb26605c723a57e5b63d24c2dd64182153a1486ca8e9f30bcba42d207f2c2a",
          "sha1": "5db2daa44fb995d19931b0c906fe20504752d9ec",
          "md5": "a843d789347c24749400166dd9fc9531"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.21.0-javadoc.jar",
          "url": "adventure-text-serializer-commons-4.21.0-javadoc.jar",
          "size": 88458,
          "sha512": "5d8186e383397bed103f59dcb2331492c1e1a1578f90cdcdbaa863e9309fea590226735d8aefc61851943089464fc0f3b2bae7ac7d7279bdeddaeca882330206",
          "sha256": "57955fa24851cd7205f29ce027ba5dbc4442c0777d61217eb74d2299962045f7",
          "sha1": "03b19902b4bd0ced29313231acd5b02db9b8d5bc",
          "md5": "689b06ea485148342690592d26b61184"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.21.0-sources.jar",
          "url": "adventure-text-serializer-commons-4.21.0-sources.jar",
          "size": 2904,
          "sha512": "5a3258174668c0543a73888c681fca14bc336b428ba4d5e3e8c7d33cce97633800e7614bb8209eccaf66df230b4e094d0c563829b8e9a503ec6c6f006ba861b4",
          "sha256": "b00dd03f7706a529d67d5d8c92e7a1f0fe21a14bc8922a1c8a461a93a4172179",
          "sha1": "32c219635097d3b3682ed9e31ecf2caf3c2985ca",
          "md5": "e62ae298cd37e172b89ae6b921342f1b"
        }
      ]
    }
  ]
}
