{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.18.0.jar",
          "url": "checker-qual-3.18.0.jar",
          "size": 222140,
          "sha512": "3988a266524504a3b3e1bd83148305ea0c8ba740569c984c2ba80cad16246ca9999d47bd88b10508f6776749ae52ab3f4bf9dceb915584ef9ae5e8fa832c504c",
          "sha256": "99d4491b3a8b810641eb2fd7d96b2869e8ca8c05b5ae2cf4bc030f65bb12c3a1",
          "sha1": "7d1ffd35973fa4c94c3aebf187a26cf0b4350281",
          "md5": "abc64881dec789241c89d9e1738fde98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.18.0.jar",
          "url": "checker-qual-3.18.0.jar",
          "size": 222140,
          "sha512": "3988a266524504a3b3e1bd83148305ea0c8ba740569c984c2ba80cad16246ca9999d47bd88b10508f6776749ae52ab3f4bf9dceb915584ef9ae5e8fa832c504c",
          "sha256": "99d4491b3a8b810641eb2fd7d96b2869e8ca8c05b5ae2cf4bc030f65bb12c3a1",
          "sha1": "7d1ffd35973fa4c94c3aebf187a26cf0b4350281",
          "md5": "abc64881dec789241c89d9e1738fde98"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.18.0-javadoc.jar",
          "url": "checker-qual-3.18.0-javadoc.jar",
          "size": 957445,
          "sha512": "47c03043b1d2e258967643ba193f8650c742a61dcf937f1e6968cabe1ed9456756b92579e0c02716e8f9c2d50551facad536b5e2210a575a78049da7d2c86f96",
          "sha256": "7ebc0e8c1e8a060487a444f62f6e8680eb03895dc7ef4982c2e551306b9c6320",
          "sha1": "8c820ba7246d72eb0e500257946d874284e017dc",
          "md5": "f083864e9a535f57b1289ce9a2bf710c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.18.0-sources.jar",
          "url": "checker-qual-3.18.0-sources.jar",
          "size": 251992,
          "sha512": "4226405eb7d6e46e5be05a750b98f0e6cbf033487bf04fcf938421f201b9e358735ea6a3e972f42518cd7aa5e841110cc1258146c4dbe1fc379e5c8a3c6029bb",
          "sha256": "b1f9cab368f4c3071f5ee2e00fb369a0075dfc27eb2812a26b011232a8ca707c",
          "sha1": "820398feae761f5940dd0d030593592c5fa3b166",
          "md5": "6cb448198521cbc8cbb906a23effa6d4"
        }
      ]
    }
  ]
}
