{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-json",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-4.21.0.jar",
          "url": "adventure-text-serializer-json-4.21.0.jar",
          "size": 16865,
          "sha512": "b3657f01cf85e8d27dd61743ee35e97c09f3b1243cbfa1ff1413cda9bcfebbbf23981f8c04914f55d719e001d584545ce46308a797643bb3bb4bb31d2d76ad52",
          "sha256": "928717b2dc7645ab616617c0bd55e80a9c0358762b590a0d3c0bbe302b2e5481",
          "sha1": "de96ddc880fffddb77c21c92220c454fb7e41823",
          "md5": "99c9d8bbe57a018ca69adbcdab779efb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-commons",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-4.21.0.jar",
          "url": "adventure-text-serializer-json-4.21.0.jar",
          "size": 16865,
          "sha512": "b3657f01cf85e8d27dd61743ee35e97c09f3b1243cbfa1ff1413cda9bcfebbbf23981f8c04914f55d719e001d584545ce46308a797643bb3bb4bb31d2d76ad52",
          "sha256": "928717b2dc7645ab616617c0bd55e80a9c0358762b590a0d3c0bbe302b2e5481",
          "sha1": "de96ddc880fffddb77c21c92220c454fb7e41823",
          "md5": "99c9d8bbe57a018ca69adbcdab779efb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-json-4.21.0-javadoc.jar",
          "url": "adventure-text-serializer-json-4.21.0-javadoc.jar",
          "size": 123129,
          "sha512": "fa80854259ac5640d79bd568ce4289e3a445994bbca7dc37abd4b279d84bfa86787399efa42a7bf9fedda80418282467ec0e72561e603f3e7aebd65800515a3e",
          "sha256": "b341f6dd23057ad5648b4673b75bb17b475edb532626e358067b6b21ea29e4f7",
          "sha1": "4fde453a0660616aea8e6a09838326769170d06a",
          "md5": "30dee0a8a4dad4291acab6b3a9ae0a07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-json-4.21.0-sources.jar",
          "url": "adventure-text-serializer-json-4.21.0-sources.jar",
          "size": 12538,
          "sha512": "26a69ec36007d61066113ced3f4f49d149e3c9aec418667bd392084a4c9108c8ca7624cc1be1178ade1e70c4b8c7be32c1f454d1908f1f6d60ff4e389bd4b776",
          "sha256": "8a0cf03cb633b0f7606c25db4201a0ca09786a4f40aba68926715514d24224a7",
          "sha1": "37cb99664937caed46f5be2bf1dcbd61bb8f2cee",
          "md5": "381ae7dd879120ce49b17a2f43556b37"
        }
      ]
    }
  ]
}
