{
  "formatVersion": "1.1",
  "component": {
    "group": "net.luckperms",
    "module": "api",
    "version": "5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-5.4.jar",
          "url": "api-5.4.jar",
          "size": 142302,
          "sha512": "a57d5bc82de2c39978d2191e06f8543ba5c96c67d73e2e73ed137f0c82aac2e7464d4d98d96a46abe6ea9b872789a77732699b1adf20e6f61ad0e1f8048853a1",
          "sha256": "086e3971ea63c0b5ad567881b2dfd955acbbffa24fe85ceac8abf54b114ce986",
          "sha1": "7b07573b0c9f06a1e5ddfc6b0042d04759d0ba8a",
          "md5": "b883d83ba5feb4c0f8caf8cdbdffbb46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-5.4.jar",
          "url": "api-5.4.jar",
          "size": 142302,
          "sha512": "a57d5bc82de2c39978d2191e06f8543ba5c96c67d73e2e73ed137f0c82aac2e7464d4d98d96a46abe6ea9b872789a77732699b1adf20e6f61ad0e1f8048853a1",
          "sha256": "086e3971ea63c0b5ad567881b2dfd955acbbffa24fe85ceac8abf54b114ce986",
          "sha1": "7b07573b0c9f06a1e5ddfc6b0042d04759d0ba8a",
          "md5": "b883d83ba5feb4c0f8caf8cdbdffbb46"
        }
      ]
    }
  ]
}
