{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-commons",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.24.0.jar",
          "url": "adventure-text-serializer-commons-4.24.0.jar",
          "size": 2594,
          "sha512": "0f143bbde146711567d676ee4f2a016ff2f69c50515240074be902d6d00629319948e4bf6a90c010f9ff0e4afcb831bf1d8b99514acf41be6d62fb01ec464ee9",
          "sha256": "1010202c73124d3e0789dfdabb2778a5fb8cfad8726d70af9beb5c5759d4ccfd",
          "sha1": "9f5a467ba9db7946139a22d19187d678112546b3",
          "md5": "0a5b1a93255d986f82258ca541f5c3c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.24.0.jar",
          "url": "adventure-text-serializer-commons-4.24.0.jar",
          "size": 2594,
          "sha512": "0f143bbde146711567d676ee4f2a016ff2f69c50515240074be902d6d00629319948e4bf6a90c010f9ff0e4afcb831bf1d8b99514acf41be6d62fb01ec464ee9",
          "sha256": "1010202c73124d3e0789dfdabb2778a5fb8cfad8726d70af9beb5c5759d4ccfd",
          "sha1": "9f5a467ba9db7946139a22d19187d678112546b3",
          "md5": "0a5b1a93255d986f82258ca541f5c3c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.24.0-javadoc.jar",
          "url": "adventure-text-serializer-commons-4.24.0-javadoc.jar",
          "size": 87699,
          "sha512": "cc4fe99d774e95a95f1e181f4aecef8e68ffca026248826650de43c2e60b64e568e385a123cb9a79400b92b53a7a5f41702e39000589ec60b4f4eea24f50edca",
          "sha256": "11c7362ff116f69b9aea25fa0e08a5f46e5e89fef4191dd4e4a37b2b12d96957",
          "sha1": "89dd8900d7810b10a1d8cd318b0df3363e622e26",
          "md5": "fa98296a545546e5ef6ce13e5ce1b63c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-commons-4.24.0-sources.jar",
          "url": "adventure-text-serializer-commons-4.24.0-sources.jar",
          "size": 2918,
          "sha512": "f83e319f6576b782671448b4de082dd92dbbfc44b013ab78e118db3a5a36b856b77145d82570874f3eac579428e95c082578c06ff79187f4dd7b4df0c7b940b3",
          "sha256": "65c13015dfe739bd78e9b3d87e3b5b6913516d3b08fc69e11915300ca858f34a",
          "sha1": "d4dd39b74b09b917549afd1020a1872fb9cf6187",
          "md5": "e063d4eef460e65de4f29b226c1c5cc7"
        }
      ]
    }
  ]
}
