{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "8.4"
    }
  },
  "component" : {
    "group" : "com.github.Exlll",
    "module" : "ConfigLib",
    "version" : "v4.5.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "com.github.Exlll.ConfigLib",
      "module" : "configlib-yaml",
      "version" : {
        "requires" : "v4.5.0"
      }
    } ],
    "files" : [ {
      "name" : "configlib-paper-v4.5.0.jar",
      "url" : "configlib-paper-v4.5.0.jar",
      "size" : 3035,
      "sha512" : "95c0ed3db9656f634274ab00bf464a484716c14a841dae11d30f1062d411608b5b3b20639b5c27c0098a5bfb68735df63a06264660bc1b8d1f27d73d080b3645",
      "sha256" : "2a62a6857a91e756846f812cf59e6263341221705d8cc57af15db9e3f0bc6b63",
      "sha1" : "35fd286d1aba1a191fd9b9d323b94f538127251d",
      "md5" : "0a5499d693c27d296d24fd71db50f2f2"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.Exlll.ConfigLib",
      "module" : "configlib-yaml",
      "version" : {
        "requires" : "v4.5.0"
      }
    } ],
    "files" : [ {
      "name" : "configlib-paper-v4.5.0.jar",
      "url" : "configlib-paper-v4.5.0.jar",
      "size" : 3035,
      "sha512" : "95c0ed3db9656f634274ab00bf464a484716c14a841dae11d30f1062d411608b5b3b20639b5c27c0098a5bfb68735df63a06264660bc1b8d1f27d73d080b3645",
      "sha256" : "2a62a6857a91e756846f812cf59e6263341221705d8cc57af15db9e3f0bc6b63",
      "sha1" : "35fd286d1aba1a191fd9b9d323b94f538127251d",
      "md5" : "0a5499d693c27d296d24fd71db50f2f2"
    } ]
  }, {
    "name" : "javadocElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "javadoc",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-paper-v4.5.0.jar",
      "url" : "configlib-paper-v4.5.0.jar",
      "size" : 74671,
      "sha512" : "6ea7f9ebbe17b05f929d51cc02331477904433e8c8aea1ef7c8b6f98441f7bf4efea75a90efb72b9ba70daac19629be197416152656a446815c7011404075c11",
      "sha256" : "60242789315c8835396cafc98fb5f0ca2655c26128e3b123812ac5dd54c7f962",
      "sha1" : "b68a2c289d0a286d63589dafae9bce6d4c90b5c7",
      "md5" : "a931025e7489786ffea2fb6bc7862d5e"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-paper-v4.5.0.jar",
      "url" : "configlib-paper-v4.5.0.jar",
      "size" : 2055,
      "sha512" : "c6ab92d8e78212061fa4e00de4ac39a7ea2e6a17eaa451c7dfe34c84a256d5165d433888b12cd2524af5cb349cf8600c8b1054089fb371947e0f6007f8815e0b",
      "sha256" : "f92cd7263e34e39decccf40f5ee2066aa26348fa40f91f042db5b163740e2eb5",
      "sha1" : "d5e99cb177c73484af4114ca92f1156b9e2d7e73",
      "md5" : "7fcb591582dc443f354f87bae3450377"
    } ]
  } ]
}