{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.goooler.shadow",
    "module": "shadow-gradle-plugin",
    "version": "8.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "shadow-gradle-plugin-8.1.7.jar",
          "url": "shadow-gradle-plugin-8.1.7.jar",
          "size": 358422,
          "sha512": "511e3f12ee55b82f5e18ca19c4ea8c2debb7f7fb594c2d071ccfa2d6e84e9c1d8d86d982eae421de2eece6ae2f177c03c78dc3661e4dc89cb9e6ad98b71cda35",
          "sha256": "8f2267ef1cbb65e55c45f972422fbc011cae68a02bb4d68d4011f66f7590eea5",
          "sha1": "6564dbea6101f7e8cb148ad83f62c11bd708fb78",
          "md5": "d7e815f06b9450db167eb26783302920"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-xml",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdependency",
          "version": {
            "requires": "2.10"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "shadow-gradle-plugin-8.1.7.jar",
          "url": "shadow-gradle-plugin-8.1.7.jar",
          "size": 358422,
          "sha512": "511e3f12ee55b82f5e18ca19c4ea8c2debb7f7fb594c2d071ccfa2d6e84e9c1d8d86d982eae421de2eece6ae2f177c03c78dc3661e4dc89cb9e6ad98b71cda35",
          "sha256": "8f2267ef1cbb65e55c45f972422fbc011cae68a02bb4d68d4011f66f7590eea5",
          "sha1": "6564dbea6101f7e8cb148ad83f62c11bd708fb78",
          "md5": "d7e815f06b9450db167eb26783302920"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-backports-compat23",
          "version": {
            "requires": "3.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "shadow-gradle-plugin-8.1.7-all.jar",
          "url": "shadow-gradle-plugin-8.1.7-all.jar",
          "size": 8458250,
          "sha512": "ed01a51e938d431d1ea4bb6b3d9f968535b544e313ba67b7114aea806f670a275db1d815f87a8189b0951c87ddc366c9bc06e17690630f253cd18a0ca3074708",
          "sha256": "bad43b2354363e95343fef6e42e03c159b421425780e2ada90bc2ddca88829d5",
          "sha1": "33a0ecf325932eb9db900e4087a959f1a184e63f",
          "md5": "1d451008bfe1ca25f1fb1f06f051a454"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shadow-gradle-plugin-8.1.7-javadoc.jar",
          "url": "shadow-gradle-plugin-8.1.7-javadoc.jar",
          "size": 99902,
          "sha512": "56961a348503c5d391225bdddce2b1e40781da3c5d045e7270f1b17099fcc475d4421a035b5a5b2049d716a87d17ab0c2f9c39d1c44c8ecb2db008ff944ad82a",
          "sha256": "6169f65780d59161d754e62a1433927c0942bbe2d8d20c430ed4d0fdfe084b85",
          "sha1": "ce7eb3220d0eb5fb8dd4f6e85e3a0cfba5c2ba19",
          "md5": "3c679a07fbcc2e9e8be34e47ad26a716"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shadow-gradle-plugin-8.1.7-sources.jar",
          "url": "shadow-gradle-plugin-8.1.7-sources.jar",
          "size": 64054,
          "sha512": "69a8412becdb874f8e8cebf247f367bb191d1c453b3ae4195ba23d81c508acfcebab7b4d8ecf863930c3f61a9e444efd237fd067f44e44a0fd6f212477d96f29",
          "sha256": "54d1a4613c3e668791701939ddb38c099b5d0dd2b18176365be37255ee5ab6e1",
          "sha1": "9e79db01266cc629a8674df6acd60d6d730db0e3",
          "md5": "62bcf933cac3b321d3f3e7f072ca6288"
        }
      ]
    }
  ]
}
