{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.21.0.jar",
          "url": "adventure-api-4.21.0.jar",
          "size": 419800,
          "sha512": "4a638dade5fd4915dbd1e7d6ef7ac7c860c6365ece8699a0bafd11be6acd3c6d8e28d891be2e4747fcd2b8bbd0b18d47e4b08e4b0b6c18123614500c06dab579",
          "sha256": "64a765760401e78d433a87dbd4cda57016b303853c6fd1dc97087b5a3aa68133",
          "sha1": "12cbccf2de584413f039d2379f6cb223c891dda2",
          "md5": "0d161e2e7813244f871599cfbc7aea4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.21.0.jar",
          "url": "adventure-api-4.21.0.jar",
          "size": 419800,
          "sha512": "4a638dade5fd4915dbd1e7d6ef7ac7c860c6365ece8699a0bafd11be6acd3c6d8e28d891be2e4747fcd2b8bbd0b18d47e4b08e4b0b6c18123614500c06dab579",
          "sha256": "64a765760401e78d433a87dbd4cda57016b303853c6fd1dc97087b5a3aa68133",
          "sha1": "12cbccf2de584413f039d2379f6cb223c891dda2",
          "md5": "0d161e2e7813244f871599cfbc7aea4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.21.0-javadoc.jar",
          "url": "adventure-api-4.21.0-javadoc.jar",
          "size": 839216,
          "sha512": "5d4f3f25b2055fd19273439b750cb8f75af137896aea080401805f56b817b85bf0fc9591c2e7a69d4bc01d3c693c7cdf79e6e174b6d590a87e388c1154450ee8",
          "sha256": "00ee593b1972b4a9aa1c83e800ee60b36645ec3f0ff5864785c997e239fe29fe",
          "sha1": "1fed61b3c6dade2021e685418f69b3dd3fdaa8c7",
          "md5": "9071127e04feb9b47f17b8d972b1903a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-api-4.21.0-sources.jar",
          "url": "adventure-api-4.21.0-sources.jar",
          "size": 334401,
          "sha512": "2ac5e8677caa54fe851b997888ee75cd5aa1810df34cdb8ca9f6caff7f050f5a855785404f0c817c7b1db2f5582e5bd1b8ba6c3ebc573fcca33e932f570da897",
          "sha256": "2c7147dc1bc8cbe876570133df391ea4e9ef300c8cb6d891dbbf3801a5e54e18",
          "sha1": "6185e3c886e8e3f998ba2bc3f06eb9c14e742dec",
          "md5": "0d890b4ce4d3a6c4e85ed5b461c3d68a"
        }
      ]
    }
  ]
}
