{
  "formatVersion": "1.1",
  "component": {
    "group": "club.minnced",
    "module": "opus-java",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "club.minnced",
          "module": "opus-java-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "club.minnced",
          "module": "opus-java-natives",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "opus-java-1.1.1.jar",
          "url": "opus-java-1.1.1.jar",
          "size": 261,
          "sha512": "196d8252e63da31a9e6485b0cab26bcfe52c8bacf13e7f5bc7c360c866ac42c97b05ee5c2f88548f69ef8d7e340b292bfb5f71f473a58344157daaf6dcfebc76",
          "sha256": "85b93eb42198eb63613b16e5ba5d761397aa9140147cc8415b996f8833344cbd",
          "sha1": "6656bf7d92e3bc058beb8f0f8a14fe9bc02da4b8",
          "md5": "86e5d32e96eb516138cbc95ccb6d9c18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "club.minnced",
          "module": "opus-java-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "club.minnced",
          "module": "opus-java-natives",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "opus-java-1.1.1.jar",
          "url": "opus-java-1.1.1.jar",
          "size": 261,
          "sha512": "196d8252e63da31a9e6485b0cab26bcfe52c8bacf13e7f5bc7c360c866ac42c97b05ee5c2f88548f69ef8d7e340b292bfb5f71f473a58344157daaf6dcfebc76",
          "sha256": "85b93eb42198eb63613b16e5ba5d761397aa9140147cc8415b996f8833344cbd",
          "sha1": "6656bf7d92e3bc058beb8f0f8a14fe9bc02da4b8",
          "md5": "86e5d32e96eb516138cbc95ccb6d9c18"
        }
      ]
    }
  ]
}
