{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-plain",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-plain-4.24.0.jar",
          "url": "adventure-text-serializer-plain-4.24.0.jar",
          "size": 13034,
          "sha512": "3dc577492dc6fb1de3d5119fe6cc9181d06bdad8408aba1352bb9da11dd7e51b6b0eb2d99ed250cc3e8d9a1759f4b3759377aba69e68ba407836004065a72f4c",
          "sha256": "7e52a98e590d088ff07be1f8b0e759864717466fd35db1862fbb6ebb41b245db",
          "sha1": "dc075cfc900a6660c1f20fc29650f322a85754a2",
          "md5": "dd1142ec95beac40f2188e54d51001fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-plain-4.24.0.jar",
          "url": "adventure-text-serializer-plain-4.24.0.jar",
          "size": 13034,
          "sha512": "3dc577492dc6fb1de3d5119fe6cc9181d06bdad8408aba1352bb9da11dd7e51b6b0eb2d99ed250cc3e8d9a1759f4b3759377aba69e68ba407836004065a72f4c",
          "sha256": "7e52a98e590d088ff07be1f8b0e759864717466fd35db1862fbb6ebb41b245db",
          "sha1": "dc075cfc900a6660c1f20fc29650f322a85754a2",
          "md5": "dd1142ec95beac40f2188e54d51001fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-plain-4.24.0-javadoc.jar",
          "url": "adventure-text-serializer-plain-4.24.0-javadoc.jar",
          "size": 98097,
          "sha512": "30c80acb6a6a2045ee28fae857235d6c2d3f361e43318799d378d1cb421793b70c46edb2a27677fe319d718a487a09817a2bfa288cb04ea97b583141deed435d",
          "sha256": "893f95ab43a6a163bf46890931c1a76429c61dc9739dbd2a0c31408aecb90645",
          "sha1": "7196943281c4ec1f0ff8d5a52d9c3ab5885a40f0",
          "md5": "6783a0c4593e6665fefaeab1e064f76d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-plain-4.24.0-sources.jar",
          "url": "adventure-text-serializer-plain-4.24.0-sources.jar",
          "size": 9024,
          "sha512": "7e73994152ed353233f722fafd6eb6ddc75a763fab7755fcbfeb392b9ef3cebed36ead3831d3008ef8b19e27d48fbbe4e52c4a5012153cf1fe3a8d9c19148fe5",
          "sha256": "51c8a77b3782b4416b59866464471c7088e412185f45460988d6d7e13820d917",
          "sha1": "0c9d79cb89e5ad37989785b46490f80dde1b4a81",
          "md5": "6c52c95d025c9d3c7ff7df6738a6928a"
        }
      ]
    }
  ]
}
