{
  "formatVersion": "1.1",
  "component": {
    "group": "io.papermc.paper",
    "module": "paper-api",
    "version": "1.17.1-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.16-R0.4"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.9.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "paper-api-1.17.1-R0.1-SNAPSHOT.jar",
          "url": "paper-api-1.17.1-R0.1-SNAPSHOT.jar",
          "size": 1694176,
          "sha512": "c0073156fbdd709c103a1d0c86ff6e2bb4bba4bed2125e38c45ae85e857e48ecb3ab9ccfd6045eaa716f815b32663f031abdcdba94b073889daca771274068f8",
          "sha256": "f14a166ca4514e9d8050cf064dad80f5299c406129e58456ff786e7a6afa2493",
          "sha1": "00ba8a242c22b6f74c19f834096e02ec955d5b0f",
          "md5": "255a2f49fce79bcd4fa8a99bc8c16383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.16-R0.4"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.9.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        }
      ],
      "files": [
        {
          "name": "paper-api-1.17.1-R0.1-SNAPSHOT.jar",
          "url": "paper-api-1.17.1-R0.1-SNAPSHOT.jar",
          "size": 1694176,
          "sha512": "c0073156fbdd709c103a1d0c86ff6e2bb4bba4bed2125e38c45ae85e857e48ecb3ab9ccfd6045eaa716f815b32663f031abdcdba94b073889daca771274068f8",
          "sha256": "f14a166ca4514e9d8050cf064dad80f5299c406129e58456ff786e7a6afa2493",
          "sha1": "00ba8a242c22b6f74c19f834096e02ec955d5b0f",
          "md5": "255a2f49fce79bcd4fa8a99bc8c16383"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paper-api-1.17.1-R0.1-SNAPSHOT-sources.jar",
          "url": "paper-api-1.17.1-R0.1-SNAPSHOT-sources.jar",
          "size": 1203816,
          "sha512": "ee83dcddf5a2c6d624cb815a0e234178c0ab21d6b7ba7b24b2cf458814749d2fdec75a1923819eb69cf448ebfb19ad7f6d3497f5c4a1ec32d8dabb2802c1453f",
          "sha256": "62899e083454b8ee5224b2aaccc5416cd0cecec7c446ce2dd8a722dd0e8db72c",
          "sha1": "3d98a859edf14f1ff90e133afef454885f871f6d",
          "md5": "c1a2dcb438ce7a53625b070aa5314aa6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paper-api-1.17.1-R0.1-SNAPSHOT-javadoc.jar",
          "url": "paper-api-1.17.1-R0.1-SNAPSHOT-javadoc.jar",
          "size": 6651674,
          "sha512": "b38ec7de96aaabe6844314e4139fd6260f95758a2f1710a4d23620974a0e3d65ee72ee99f4b270a5a6e7623dea6788479e80e24960196a19fc5e3ebf4cb92e9f",
          "sha256": "e2a69f4ecd9f9fb854d5342daade67c1f2215245defd1dc04fd95c4012760acd",
          "sha1": "b26b7ed2ca3d56d8b08eea1f13f0a99cf8e39e0e",
          "md5": "b887d0ba92b710f41b4347d684b50b53"
        }
      ]
    }
  ]
}
