{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-platform-viaversion",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.viaversion",
          "module": "viaversion-api",
          "version": {
            "requires": "4.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-viaversion-4.4.1.jar",
          "url": "adventure-platform-viaversion-4.4.1.jar",
          "size": 20272,
          "sha512": "1fcb3edf648cc931b0a4db166c064a53ff5aeaa4073ac538c8b96b91961ac4c54673418ce8b2056bc6e782234e0a22c1def8d2e7c36f85dbe755d9633d8807a4",
          "sha256": "df463083060a51403df0cfe3e08e3c8890103bfc707e9235f6279e87c619753f",
          "sha1": "f88d6816a53f4c3a43f76de0a9ee7cd50f5f397f",
          "md5": "d7330e3e448ffe72c67cb2fb9f4dff49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-platform-facet",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.21.0"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "adventure-platform-viaversion-4.4.1.jar",
          "url": "adventure-platform-viaversion-4.4.1.jar",
          "size": 20272,
          "sha512": "1fcb3edf648cc931b0a4db166c064a53ff5aeaa4073ac538c8b96b91961ac4c54673418ce8b2056bc6e782234e0a22c1def8d2e7c36f85dbe755d9633d8807a4",
          "sha256": "df463083060a51403df0cfe3e08e3c8890103bfc707e9235f6279e87c619753f",
          "sha1": "f88d6816a53f4c3a43f76de0a9ee7cd50f5f397f",
          "md5": "d7330e3e448ffe72c67cb2fb9f4dff49"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.viaversion",
          "module": "viaversion-api",
          "version": {
            "requires": "4.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-platform-viaversion-4.4.1-javadoc.jar",
          "url": "adventure-platform-viaversion-4.4.1-javadoc.jar",
          "size": 345133,
          "sha512": "7d961c07701cccef77165da29c6ac1230ddfe40b5972635fe8151fef2855c1ef3e05569aa001199bb6dfda7d63abbe1e1cd50f81116b2531508d32d3e2f1ed9a",
          "sha256": "a70d3b82712c374b0135bba65216bdfecf964c1071b30e5e97bcc989c296125b",
          "sha1": "af3aa6c5815a2ee85d80bf43c59f50bc1840b29e",
          "md5": "d66dd1d9fe94c6b72c771d1eb52fa1f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-platform-viaversion-4.4.1-sources.jar",
          "url": "adventure-platform-viaversion-4.4.1-sources.jar",
          "size": 5932,
          "sha512": "4bb6c84030e8b7ca3a5ea4268bf1a6daa709624a63aa409d1a8334c26027008d3459027e27e102abff65edc9ab8ace0414459f7d71c3540a957465aa499c97c3",
          "sha256": "450f0b91982af0afdf0dfb313359f571546927084ef25fc3828921fe8d383f9c",
          "sha1": "c8c474c15c41c2cb80941d4dcb5058b91901926e",
          "md5": "5cb12ce91fe6984c7a2655d52b6dedbd"
        }
      ]
    }
  ]
}
