{
  "formatVersion": "1.1",
  "component": {
    "group": "me.clip",
    "module": "placeholderapi",
    "version": "2.11.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "placeholderapi-2.11.7.jar",
          "url": "placeholderapi-2.11.7.jar",
          "size": 953837,
          "sha512": "73c92097ad5e1ef3e2f65bff2c1f180834e10d9e4eab9e928ae594d310dfd6ba8db0bd2899ce8ce769c8e1eecf36fd469d668202b18455701f44f34ca8da8831",
          "sha256": "f5a4ea718baaab6118cfe8f3983ea3a5660af1ee8572360182a3d1b6dbf2eb5d",
          "sha1": "f6e2e8f8054ec797fe20b08ec81a44574bdced50",
          "md5": "4c290534922fe5cc95e2ceb278e593e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bstats",
          "module": "bstats-bukkit",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-bukkit",
          "version": {
            "requires": "4.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "placeholderapi-2.11.7.jar",
          "url": "placeholderapi-2.11.7.jar",
          "size": 953837,
          "sha512": "73c92097ad5e1ef3e2f65bff2c1f180834e10d9e4eab9e928ae594d310dfd6ba8db0bd2899ce8ce769c8e1eecf36fd469d668202b18455701f44f34ca8da8831",
          "sha256": "f5a4ea718baaab6118cfe8f3983ea3a5660af1ee8572360182a3d1b6dbf2eb5d",
          "sha1": "f6e2e8f8054ec797fe20b08ec81a44574bdced50",
          "md5": "4c290534922fe5cc95e2ceb278e593e2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "placeholderapi-2.11.7.jar",
          "url": "placeholderapi-2.11.7.jar",
          "size": 953837,
          "sha512": "73c92097ad5e1ef3e2f65bff2c1f180834e10d9e4eab9e928ae594d310dfd6ba8db0bd2899ce8ce769c8e1eecf36fd469d668202b18455701f44f34ca8da8831",
          "sha256": "f5a4ea718baaab6118cfe8f3983ea3a5660af1ee8572360182a3d1b6dbf2eb5d",
          "sha1": "f6e2e8f8054ec797fe20b08ec81a44574bdced50",
          "md5": "4c290534922fe5cc95e2ceb278e593e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "placeholderapi-2.11.7-javadoc.jar",
          "url": "placeholderapi-2.11.7-javadoc.jar",
          "size": 395276,
          "sha512": "e784b50a9656e33b392b44a46ec06394f1de6f637dbaae69de7d2eeb1f82b8d5712dbae46a9c1f9d26b4d9b7ffa0d67ed9119d6202a5efc95a6c5ea69f2724fc",
          "sha256": "99e8ac16d18c7937eb956c9fcad108cb9ce0593a3f7c87b9a167e5cda2b97755",
          "sha1": "56678031997b19b3aa76038f89c3bb8e22248dfe",
          "md5": "938471d96526dd932593bd82ff95ab26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "placeholderapi-2.11.7-sources.jar",
          "url": "placeholderapi-2.11.7-sources.jar",
          "size": 97017,
          "sha512": "a43e304ea2b844e0db8d16906cfa22a102de7e2a973d760323497929ce17c620431e388e71c571d917311ee496dac3cb56ea172d0c189257602ebbcf1d37e333",
          "sha256": "eefab771a6df9ac6b2188b65efb5bbac583a3ce6f054a97c532a81ba9e81f156",
          "sha1": "157993b356f09a31efe7f5f312afa1c6cf29b4fe",
          "md5": "2944b459852007b5038ae31dc3121691"
        }
      ]
    }
  ]
}
