{
  "formatVersion": "1.1",
  "component": {
    "group": "net.essentialsx",
    "module": "NMSReflectionProvider",
    "version": "2.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bukkit",
          "module": "bukkit",
          "version": {
            "requires": "1.12.2-R0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "NMSReflectionProvider-2.21.0.jar",
          "url": "NMSReflectionProvider-2.21.0.jar",
          "size": 30563,
          "sha512": "fb512b3fa459f9276be479cc89e85dba600ba9eaa36712faa27bfbb49a20c179d8a4db75f135f776b3a7f2477788d9ae8c5c2dd833d2f3af3c5280fa8ea985b0",
          "sha256": "0c565ea3967cf9b30ad27b5e1d3fefef34f63fe16a209b3d695339e9e0dee46b",
          "sha1": "03dbd4cf72ecfb1394ef9287afe80409be331b8f",
          "md5": "cbf8434d543bd0ff2879b71fa7510c8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.essentialsx",
          "module": "BaseProviders",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "org.bukkit",
          "module": "bukkit",
          "version": {
            "requires": "1.12.2-R0.1-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          },
          "reason": "Bukkit API ships old versions, Configurate requires modern versions"
        }
      ],
      "files": [
        {
          "name": "NMSReflectionProvider-2.21.0.jar",
          "url": "NMSReflectionProvider-2.21.0.jar",
          "size": 30563,
          "sha512": "fb512b3fa459f9276be479cc89e85dba600ba9eaa36712faa27bfbb49a20c179d8a4db75f135f776b3a7f2477788d9ae8c5c2dd833d2f3af3c5280fa8ea985b0",
          "sha256": "0c565ea3967cf9b30ad27b5e1d3fefef34f63fe16a209b3d695339e9e0dee46b",
          "sha1": "03dbd4cf72ecfb1394ef9287afe80409be331b8f",
          "md5": "cbf8434d543bd0ff2879b71fa7510c8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NMSReflectionProvider-2.21.0-javadoc.jar",
          "url": "NMSReflectionProvider-2.21.0-javadoc.jar",
          "size": 136601,
          "sha512": "4bc30577fb7807eca201f8a978a3c7c343183c37e4e97d10bed85b076da14383894ea0cae9ec65a68e9a61276f7e902430eaeddfd5447ac87514bf85b97b54ec",
          "sha256": "58a49c590afe3c0a81e68b1b9886670e775dfcc8a82ec9cb761f5093e2c799ff",
          "sha1": "d481f838b5b8892d3c04df83da186fe578100045",
          "md5": "3c252a00480ab6b206406af603a0141e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NMSReflectionProvider-2.21.0-sources.jar",
          "url": "NMSReflectionProvider-2.21.0-sources.jar",
          "size": 15627,
          "sha512": "50074a71fbfc6a4a2579702d70f2712521d09c890c38cf1dc002f81bcbf21eec07c4981a6f434efd067f334cb9d39f047fd5d2b69ae26bff29a683b92dbdb586",
          "sha256": "69a8dbc55baf85b1ad700524c5ed7043cf760080e0e9f710876cb26c2cab3ef7",
          "sha1": "df26119747cb62549114219fc1d2ed69c28bbb5f",
          "md5": "62ae74c13225c4e7e003190941213dcb"
        }
      ]
    }
  ]
}
