{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-nbt",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.21.0.jar",
          "url": "adventure-nbt-4.21.0.jar",
          "size": 102876,
          "sha512": "ace9bfe4c30fff3a5d5eed140473e62fd57fc70c9fc23a61c9df675c309374174f3ddfa55a448595077d45dfbc235302bfd3ac4ce59aaddc6e514e0526578e0e",
          "sha256": "af6ec05f168294a2e688bb3c5211b123bd0d4d78791e24bb7f1139ad98b5eb35",
          "sha1": "c3c3780298ccba6095cd4a1d2a34000deaeccb9e",
          "md5": "32a748f0271f03d2131f299bda56652f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.21.0.jar",
          "url": "adventure-nbt-4.21.0.jar",
          "size": 102876,
          "sha512": "ace9bfe4c30fff3a5d5eed140473e62fd57fc70c9fc23a61c9df675c309374174f3ddfa55a448595077d45dfbc235302bfd3ac4ce59aaddc6e514e0526578e0e",
          "sha256": "af6ec05f168294a2e688bb3c5211b123bd0d4d78791e24bb7f1139ad98b5eb35",
          "sha1": "c3c3780298ccba6095cd4a1d2a34000deaeccb9e",
          "md5": "32a748f0271f03d2131f299bda56652f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-nbt-4.21.0-javadoc.jar",
          "url": "adventure-nbt-4.21.0-javadoc.jar",
          "size": 187171,
          "sha512": "472d79e085bc35bc857752ab30b125d839e17c63c325dc0a40db3c7be7dab901d252fdd425c0a4ff77cc1950c669de22691e49322b63a79965004bf543a064eb",
          "sha256": "7b56e865dc4f420faac15f0c6ef569b5e47224e08266b34223543d387ce7f5f2",
          "sha1": "0496d627c004b6e4e4a83c0b1c362dddbb683642",
          "md5": "e6d517522a9cea37143165e45f826e50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-nbt-4.21.0-sources.jar",
          "url": "adventure-nbt-4.21.0-sources.jar",
          "size": 86551,
          "sha512": "128cf7b8052d9c08b3c1c1e9ef66c80288fa318d5026ccbe1bc49c1fe46f8dc94fa4924ca4c3ffbe9d325ae3a37bb1d550494027cfca73f23d8be3df6bd4ca58",
          "sha256": "e21ac258179d74ed2f099da4abc261ef6d9dea902892d8cb683b64c6e70a9df5",
          "sha1": "2c14dd39cad0176ea68017057c99db2d79f7683d",
          "md5": "ddcb865694faa7fff2584a1b1891afb3"
        }
      ]
    }
  ]
}
