{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-serializer-legacy",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.21.0.jar",
          "url": "adventure-text-serializer-legacy-4.21.0.jar",
          "size": 29779,
          "sha512": "53b158d52fbf81900d2c6607306b40034d3f23a2c412bb3933e0159df49aab2bbc6cb96f66b99226a38f805cc35ea7f276facccf5620948aaeba226b310b2406",
          "sha256": "9ac1b99f828458e19008f675781a0e8c8517cdfa22a1fc5bb87a7bf69554c35c",
          "sha1": "450ded487f7b85e083ca8e9572b334e089a65795",
          "md5": "d875c3e6d8f4d896705d33657f55c05d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.21.0.jar",
          "url": "adventure-text-serializer-legacy-4.21.0.jar",
          "size": 29779,
          "sha512": "53b158d52fbf81900d2c6607306b40034d3f23a2c412bb3933e0159df49aab2bbc6cb96f66b99226a38f805cc35ea7f276facccf5620948aaeba226b310b2406",
          "sha256": "9ac1b99f828458e19008f675781a0e8c8517cdfa22a1fc5bb87a7bf69554c35c",
          "sha1": "450ded487f7b85e083ca8e9572b334e089a65795",
          "md5": "d875c3e6d8f4d896705d33657f55c05d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.21.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.21.0-javadoc.jar",
          "url": "adventure-text-serializer-legacy-4.21.0-javadoc.jar",
          "size": 107056,
          "sha512": "258377cd33f4b5de882a324ab8f7e14a8e0ef73aa267702e23d4c613ff674c59ec46a2118050b909c51168aa3335c7d3db659581f98993ff0fdd5ffb6a084761",
          "sha256": "b24db7f52c28905fab90909607d19d746d69f6ec8a10fdc4fae915b1f2f017fd",
          "sha1": "324861a4aec7db6620cd0b631f2335c514b34db3",
          "md5": "1ccdd5cfc4ce49f818cb5e505335e028"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-serializer-legacy-4.21.0-sources.jar",
          "url": "adventure-text-serializer-legacy-4.21.0-sources.jar",
          "size": 18534,
          "sha512": "abfb5a428ae16ae19f640e997bdcaecdd801af3b9c0809f79b7fbf3f8c0181286ba5452646b216417b16deee041534345385f6f0c1a3ff9045c4eed38c8098df",
          "sha256": "ecd0dec2c390653081b6b533b2422bdad8fdaf562f071bb24c0d46501d0ac8da",
          "sha1": "82501fc88f4ec8655ae19936975295f9f9bf53fb",
          "md5": "b18f847d8567476ec3278143ab95047c"
        }
      ]
    }
  ]
}
