{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-api",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.24.0.jar",
          "url": "adventure-api-4.24.0.jar",
          "size": 436164,
          "sha512": "82dfb7302e539837e5b5780de7e2acaeafb3aa004672cea646673aa67dbf67dd44fa3e703ea9dd7a052ce9ff97c30c5a7cd645af430d3b57e4fc2737eb96730f",
          "sha256": "d8c1d66db0fbaf084e8179b3f2541d9ff64402a7881070a71e8b3c26c26d384e",
          "sha1": "af2ff93942f237befc88e44140229afcaf322d99",
          "md5": "d53eb23ef806c05dfa0f4278bc206b01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.24.0.jar",
          "url": "adventure-api-4.24.0.jar",
          "size": 436164,
          "sha512": "82dfb7302e539837e5b5780de7e2acaeafb3aa004672cea646673aa67dbf67dd44fa3e703ea9dd7a052ce9ff97c30c5a7cd645af430d3b57e4fc2737eb96730f",
          "sha256": "d8c1d66db0fbaf084e8179b3f2541d9ff64402a7881070a71e8b3c26c26d384e",
          "sha1": "af2ff93942f237befc88e44140229afcaf322d99",
          "md5": "d53eb23ef806c05dfa0f4278bc206b01"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.24.0-javadoc.jar",
          "url": "adventure-api-4.24.0-javadoc.jar",
          "size": 865638,
          "sha512": "53a0a58b46668eef079ab67d8f8cb5c85ff3c0f7e9a144d0b30c1ba4a13f3d170e5e2b39d390ac4f4b09c0b1d6700cfbcecf4e2f55fd72b8a049ff7cb981ac46",
          "sha256": "b1c4a0b5c34c0f4fc1475aaa0e7d4d7d984fe4dda090996e10f3dae1e5bcff22",
          "sha1": "e5a06773eafcb4bd13fc8586d758e90b7ef6865d",
          "md5": "bee291c503b7a2987fa5e64088a513b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-api-4.24.0-sources.jar",
          "url": "adventure-api-4.24.0-sources.jar",
          "size": 342628,
          "sha512": "0369cb7cbe70ecf0aa176837033b8f1b5f42eb612620b345f534ccdaa9b002830109acc2542a7546102ff8103263ace3700e1f4a3e3b4d34d617b379585bf7f2",
          "sha256": "1d3c76b2d5ea2fe1ad11300a922b5207b582a760b6bf7f3e11a20d9f83759c1d",
          "sha1": "8383ff26ac26a82d189a60f2f9268e180f9e1469",
          "md5": "e6dcd818cbe1d52a2b41deed63e43059"
        }
      ]
    }
  ]
}
