{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "8.4"
    }
  },
  "component" : {
    "group" : "com.github.Exlll",
    "module" : "ConfigLib",
    "version" : "v4.5.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "configlib-core-v4.5.0.jar",
      "url" : "configlib-core-v4.5.0.jar",
      "size" : 101463,
      "sha512" : "4b2261c3ba808b3a40fbe8aad4289be2dfc682a0b354b35ef36a45f273f63d3ec9352bcd750fa981acac8f668c337b9b7cf9f650a1806f51ba40e818924dbacf",
      "sha256" : "706095494054dff0740f79e82c86485ef90102cf90f0a778c896957004dd2cf3",
      "sha1" : "29ccf96a587648365a8a7589f8ee69c8c49994b4",
      "md5" : "e054f7c03122368129ea34ea52411c49"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-core-v4.5.0.jar",
      "url" : "configlib-core-v4.5.0.jar",
      "size" : 101463,
      "sha512" : "4b2261c3ba808b3a40fbe8aad4289be2dfc682a0b354b35ef36a45f273f63d3ec9352bcd750fa981acac8f668c337b9b7cf9f650a1806f51ba40e818924dbacf",
      "sha256" : "706095494054dff0740f79e82c86485ef90102cf90f0a778c896957004dd2cf3",
      "sha1" : "29ccf96a587648365a8a7589f8ee69c8c49994b4",
      "md5" : "e054f7c03122368129ea34ea52411c49"
    } ]
  }, {
    "name" : "javadocElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "javadoc",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-core-v4.5.0.jar",
      "url" : "configlib-core-v4.5.0.jar",
      "size" : 143130,
      "sha512" : "a9ad0f26e8fbfd067345839ec0f569213b335e89a71646ab6c590e2aba033b96b69189610f0b5d19cc66098e4dbb9cb638c02c6db9f38988369bbe1777bc699b",
      "sha256" : "eefb4629b935d6310e5b2fa6d05cdfbb93a5bf6abb87b312621a7f70a4cac32c",
      "sha1" : "d62bf3090bc659f8e585ca3f36e1f9befd217067",
      "md5" : "6db55d328125ae5e6fa255abdce67f43"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "configlib-core-v4.5.0.jar",
      "url" : "configlib-core-v4.5.0.jar",
      "size" : 38298,
      "sha512" : "c32e11761550939d31174abaa506a28968c8c07b957be4df40ed67aec7773081110041833328d7efd3d1cf503c2fc8c390d802c50e2364539665f48b208b9ca2",
      "sha256" : "fae26ce258882c9588fc9c65b8c042cfefbf368b864b5265e3bee0ea2301ff23",
      "sha1" : "225a48ead25751ef5d56aa55e4168f2d5fee8d37",
      "md5" : "d6bcd82787583a3d04b27756e03a44c1"
    } ]
  } ]
}